export const SortFilter = [
  {
    name: "Title",
    filter: "-title",
  },
  {
    name: "Views",
    filter: "-views",
  },
  {
    name: "Quantity",
    filter: "-qty",
  },
  {
    name: "Price",
    filter: "-price",
  },

  {
    name: "Modify Date",
    filter: "-createdAt",
  },
];

export const Category = [
  { value: "electronics", name: "Electronics" },
  { value: "faishion", name: "Faishion" },
  { value: "beauty", name: "Beauty" },
  { value: "furniture", name: "Furniture" },
  { value: "Other", name: "Other" },
];
export const SubCategory = [
  { value: "mens clothings", name: "Men's Clothing" },
  { value: "womens clothings", name: "Women's Clothing" },
  { value: "kid's clothing", name: "Kid's Clothing" },
  { value: "furniture", name: "Furniture" },
  { value: "women jwellery", name: "Women's Jwellery" },
  { value: "laptop", name: "Laptop" },
  { value: "mobile", name: "Mobile" },
  { value: "laptop accessories", name: "Laptop Accessories" },
  { value: "Mobile accessories", name: "Mobile Accessories" },
  { value: "Other", name: "Other" },
];

export const targetPeople = [
  { for: "Tech Enthusiasts", name: "Tech Enthusiasts" },
  { for: "Fitness Enthusiasts", name: "Fitness Enthusiasts" },
  { for: "Music Lovers", name: "Music Lovers" },
  { for: "Bookworms", name: "Bookworms" },
  { for: "Gamers", name: "Gamers" },
  { for: "Foodies", name: "Foodies" },
  { for: "Outdoor Adventurers", name: "Outdoor Adventurers" },
  { for: "Fashionistas", name: "Fashionistas" },
  { for: "Art Aficionados", name: "Art Aficionados" },
  { for: "Pet Lovers", name: "Pet Lovers" },
  { for: "Travel Enthusiasts", name: "Travel Enthusiasts" },
  { for: "Movie Buffs", name: "Movie Buffs" },
  { for: "Yoga Practitioners", name: "Yoga Practitioners" },
  { for: "Photography Enthusiasts", name: "Photography Enthusiasts" },
  { for: "DIY Enthusiasts", name: "DIY Enthusiasts" },
  { for: "Gardening Enthusiasts", name: "Gardening Enthusiasts" },
  { for: "History Buffs", name: "History Buffs" },
  { for: "Health and Wellness Seekers", name: "Health and Wellness Seekers" },
  { for: "Craft Beer Enthusiasts", name: "Craft Beer Enthusiasts" },
  { for: "Environmental Activists", name: "Environmental Activists" },
  { for: "Animal Rights Advocates", name: "Animal Rights Advocates" },
  { for: "Entrepreneurs", name: "Entrepreneurs" },
  { for: "Home Chefs", name: "Home Chefs" },
  { for: "Musicians", name: "Musicians" },
  { for: "Fitness Instructors", name: "Fitness Instructors" },
  { for: "Digital Nomads", name: "Digital Nomads" },
  { for: "Language Learners", name: "Language Learners" },
  { for: "Sustainability Advocates", name: "Sustainability Advocates" },
  { for: "Social Media Influencers", name: "Social Media Influencers" },
  {
    for: "Artificial Intelligence Enthusiasts",
    name: "Artificial Intelligence Enthusiasts",
  },
  { for: "Beauty Enthusiasts", name: "Beauty Enthusiasts" },
  { for: "Astronomy Enthusiasts", name: "Astronomy Enthusiasts" },
  { for: "Volunteers", name: "Volunteers" },
  { for: "Tea Connoisseurs", name: "Tea Connoisseurs" },
  { for: "Coffee Lovers", name: "Coffee Lovers" },
  { for: "Comic Book Fans", name: "Comic Book Fans" },
  { for: "Board Game Enthusiasts", name: "Board Game Enthusiasts" },
  { for: "Interior Design Enthusiasts", name: "Interior Design Enthusiasts" },
  { for: "Thrill Seekers", name: "Thrill Seekers" },
  { for: "Concertgoers", name: "Concertgoers" },
  { for: "Eco-Tourists", name: "Eco-Tourists" },
  { for: "Vintage Collectors", name: "Vintage Collectors" },
  { for: "Sneakerheads", name: "Sneakerheads" },
  { for: "Fitness Freaks", name: "Fitness Freaks" },
  { for: "Podcast Listeners", name: "Podcast Listeners" },
  { for: "Street Food Enthusiasts", name: "Street Food Enthusiasts" },
  { for: "Mountain Climbers", name: "Mountain Climbers" },
  { for: "Fashion Bloggers", name: "Fashion Bloggers" },
  { for: "History Enthusiasts", name: "History Enthusiasts" },
  { for: "Soccer Fans", name: "Soccer Fans" },
  { for: "Basketball Fans", name: "Basketball Fans" },
  { for: "Cyclists", name: "Cyclists" },
  { for: "Surfers", name: "Surfers" },
  { for: "Skateboarders", name: "Skateboarders" },
  { for: "Art Collectors", name: "Art Collectors" },
  { for: "Rock Climbers", name: "Rock Climbers" },
  { for: "Tech Start-Up Enthusiasts", name: "Tech Start-Up Enthusiasts" },
  { for: "Vegetarian/Vegan Advocates", name: "Vegetarian/Vegan Advocates" },
  { for: "Astrophotographers", name: "Astrophotographers" },
  { for: "Birdwatchers", name: "Birdwatchers" },
  { for: "Meditation Practitioners", name: "Meditation Practitioners" },
  { for: "Food Bloggers", name: "Food Bloggers" },
  { for: "Fashion Designers", name: "Fashion Designers" },
  { for: "Fitness Models", name: "Fitness Models" },
  { for: "Travel Bloggers", name: "Travel Bloggers" },
  { for: "Digital Artists", name: "Digital Artists" },
  { for: "VR Enthusiasts", name: "VR Enthusiasts" },
  { for: "Science Fiction Fans", name: "Science Fiction Fans" },
  { for: "Documentary Buffs", name: "Documentary Buffs" },
  { for: "Wine Connoisseurs", name: "Wine Connoisseurs" },
  { for: "Whiskey Aficionados", name: "Whiskey Aficionados" },
  { for: "Gin Enthusiasts", name: "Gin Enthusiasts" },
  { for: "Rum Connoisseurs", name: "Rum Connoisseurs" },
  { for: "Whale Watching Enthusiasts", name: "Whale Watching Enthusiasts" },
  { for: "Paddleboarders", name: "Paddleboarders" },
  { for: "Kite Surfers", name: "Kite Surfers" },
  { for: "Salsa Dancers", name: "Salsa Dancers" },
  { for: "Jazz Aficionados", name: "Jazz Aficionados" },
  { for: "Scuba Divers", name: "Scuba Divers" },
  { for: "Snorkelers", name: "Snorkelers" },
  { for: "Fine Dining Enthusiasts", name: "Fine Dining Enthusiasts" },
  { for: "Culinary Adventurers", name: "Culinary Adventurers" },
  { for: "Food Truck Fans", name: "Food Truck Fans" },
  { for: "Kombucha Enthusiasts", name: "Kombucha Enthusiasts" },
  { for: "Eco-Friendly Shoppers", name: "Eco-Friendly Shoppers" },
  { for: "Zero Waste Advocates", name: "Zero Waste Advocates" },
  { for: "Minimalists", name: "Minimalists" },
  { for: "Naturalists", name: "Naturalists" },
  { for: "Camping Enthusiasts", name: "Camping Enthusiasts" },
  { for: "Extreme Sports Enthusiasts", name: "Extreme Sports Enthusiasts" },
  { for: "Parkour Practitioners", name: "Parkour Practitioners" },
  { for: "Pottery Enthusiasts", name: "Pottery Enthusiasts" },
  { for: "Antique Collectors", name: "Antique Collectors" },
  { for: "Retro Gaming Enthusiasts", name: "Retro Gaming Enthusiasts" },
  { for: "Bonsai Enthusiasts", name: "Bonsai Enthusiasts" },
  { for: "Model Train Enthusiasts", name: "Model Train Enthusiasts" },
  {
    for: "Aerial Photography Enthusiasts",
    name: "Aerial Photography Enthusiasts",
  },
  { for: "Urban Explorers", name: "Urban Explorers" },
];
