export const SortFilter = [
  {
    name: "Title",
    filter: "-title",
  },
  {
    name: "Views",
    filter: "-views",
  },
  {
    name: "Quantity",
    filter: "-qty",
  },
  {
    name: "Price",
    filter: "-price",
  },

  {
    name: "Modify Date",
    filter: "-createdAt",
  },
];

export const ganderFilter = ["Men", "Women", "Kids", "Both"];
export const ageFilter = [
  {
    name: "Infant",
    ageRange: "0-1",
    age: "0+",
  },
  {
    name: "Toddler",
    ageRange: "1-3",
    age: "1+",
  },
  {
    name: "Child",
    ageRange: "3-12",
    age: "3+",
  },
  {
    name: "Teenager",
    age: "12+",
    ageRange: "12-18",
  },
  {
    name: "Young Adult",
    ageRange: "18-25",
    age: "18+",
  },
  {
    name: "Adult",
    ageRange: "25-60",
    age: "25+",
  },
  {
    name: "Older Adult",
    ageRange: "60+",
    age: "60+",
  },
];

export const Category = [
  { value: "electronics", name: "Electronics" },
  { value: "fashion", name: "Fashion" },
  { value: "beauty", name: "Beauty" },
  { value: "furniture", name: "Furniture" },
  { value: "mobiles & tablets", name: "Mobiles & Tablets" },
  { value: "home & kitchen", name: "Home & kitchen" },
  { value: "Other", name: "Other" },
];
export const SubCategoryi = [
  { value: "mens clothings", name: "Men's Clothing" },
  { value: "womens clothings", name: "Women's Clothing" },
  { value: "kid's clothing", name: "Kid's Clothing" },
  { value: "furniture", name: "Furniture" },
  { value: "women jwellery", name: "Women's Jwellery" },
  { value: "laptop", name: "Laptop" },
  { value: "mobile", name: "Mobile" },
  { value: "laptop accessories", name: "Laptop Accessories" },
  { value: "Mobile accessories", name: "Mobile Accessories" },
  { value: "Other", name: "Other" },
];

export const SubCategory = [
  // Electronics
  { value: "electronics", name: "Electronics" },
  { value: "televisions", name: "Televisions", category: "Electronics" },
  { value: "laptops", name: "Laptops", category: "Electronics" },
  { value: "cameras", name: "Cameras", category: "Electronics" },
  { value: "headphones", name: "Headphones", category: "Electronics" },
  { value: "smartwatches", name: "Smartwatches", category: "Electronics" },
  {
    value: "gaming_consoles",
    name: "Gaming Consoles",
    category: "Electronics",
  },
  { value: "audio_systems", name: "Audio Systems", category: "Electronics" },
  { value: "wearable_tech", name: "Wearable Tech", category: "Electronics" },
  { value: "home_security", name: "Home Security", category: "Electronics" },
  { value: "drones", name: "Drones", category: "Electronics" },
  { value: "accessories", name: "Accessories", category: "Electronics" },
  { value: "projectors", name: "Projectors", category: "Electronics" },
  {
    value: "networking_devices",
    name: "Networking Devices",
    category: "Electronics",
  },
  { value: "smart_home", name: "Smart Home", category: "Electronics" },
  {
    value: "storage_devices",
    name: "Storage Devices",
    category: "Electronics",
  },
  { value: "car_audio", name: "Car Audio", category: "Electronics" },
  { value: "power_banks", name: "Power Banks", category: "Electronics" },
  {
    value: "bluetooth_speakers",
    name: "Bluetooth Speakers",
    category: "Electronics",
  },

  // Fashion
  { value: "fashion", name: "Fashion" },
  { value: "mens_clothing", name: "Men's Clothing", category: "Fashion" },
  { value: "womens_clothing", name: "Women's Clothing", category: "Fashion" },
  { value: "kids_clothing", name: "Kids' Clothing", category: "Fashion" },
  { value: "footwear", name: "Footwear", category: "Fashion" },
  { value: "accessories", name: "Accessories", category: "Fashion" },
  { value: "jewelry", name: "Jewelry", category: "Fashion" },
  { value: "bags", name: "Bags", category: "Fashion" },
  { value: "sunglasses", name: "Sunglasses", category: "Fashion" },
  { value: "hats", name: "Hats", category: "Fashion" },
  { value: "scarves", name: "Scarves", category: "Fashion" },
  { value: "gloves", name: "Gloves", category: "Fashion" },
  { value: "belts", name: "Belts", category: "Fashion" },
  { value: "suits", name: "Suits", category: "Fashion" },
  { value: "activewear", name: "Activewear", category: "Fashion" },
  { value: "swimwear", name: "Swimwear", category: "Fashion" },
  { value: "sleepwear", name: "Sleepwear", category: "Fashion" },
  { value: "underwear", name: "Underwear", category: "Fashion" },
  { value: "formalwear", name: "Formalwear", category: "Fashion" },
  { value: "casualwear", name: "Casualwear", category: "Fashion" },

  // Beauty
  { value: "beauty", name: "Beauty" },
  { value: "skincare", name: "Skincare", category: "Beauty" },
  { value: "makeup", name: "Makeup", category: "Beauty" },
  { value: "hair_care", name: "Hair Care", category: "Beauty" },
  { value: "fragrances", name: "Fragrances", category: "Beauty" },
  { value: "personal_care", name: "Personal Care", category: "Beauty" },
  { value: "bath_and_body", name: "Bath & Body", category: "Beauty" },
  { value: "nail_care", name: "Nail Care", category: "Beauty" },
  { value: "mens_grooming", name: "Men's Grooming", category: "Beauty" },
  { value: "sun_protection", name: "Sun Protection", category: "Beauty" },
  { value: "anti_ageing", name: "Anti-Ageing", category: "Beauty" },
  { value: "hair_styling", name: "Hair Styling", category: "Beauty" },
  { value: "oral_care", name: "Oral Care", category: "Beauty" },
  { value: "body_care", name: "Body Care", category: "Beauty" },
  { value: "shaving", name: "Shaving", category: "Beauty" },
  { value: "bath_products", name: "Bath Products", category: "Beauty" },
  { value: "deodorants", name: "Deodorants", category: "Beauty" },
  { value: "skin_treatments", name: "Skin Treatments", category: "Beauty" },
  { value: "lip_care", name: "Lip Care", category: "Beauty" },
  { value: "eye_care", name: "Eye Care", category: "Beauty" },

  // Furniture
  { value: "furniture", name: "Furniture" },
  {
    value: "living_room_furniture",
    name: "Living Room Furniture",
    category: "Furniture",
  },
  {
    value: "bedroom_furniture",
    name: "Bedroom Furniture",
    category: "Furniture",
  },
  {
    value: "office_furniture",
    name: "Office Furniture",
    category: "Furniture",
  },
  {
    value: "dining_furniture",
    name: "Dining Furniture",
    category: "Furniture",
  },
  {
    value: "storage_solutions",
    name: "Storage Solutions",
    category: "Furniture",
  },
  {
    value: "outdoor_furniture",
    name: "Outdoor Furniture",
    category: "Furniture",
  },
  { value: "mattresses", name: "Mattresses", category: "Furniture" },
  {
    value: "furniture_accessories",
    name: "Furniture Accessories",
    category: "Furniture",
  },
  {
    value: "bedroom_accessories",
    name: "Bedroom Accessories",
    category: "Furniture",
  },
  {
    value: "living_room_accessories",
    name: "Living Room Accessories",
    category: "Furniture",
  },
  {
    value: "office_accessories",
    name: "Office Accessories",
    category: "Furniture",
  },
  {
    value: "kitchen_furniture",
    name: "Kitchen Furniture",
    category: "Furniture",
  },
  { value: "storage_units", name: "Storage Units", category: "Furniture" },
  {
    value: "childrens_furniture",
    name: "Children's Furniture",
    category: "Furniture",
  },
  {
    value: "home_office_furniture",
    name: "Home Office Furniture",
    category: "Furniture",
  },
  {
    value: "entryway_furniture",
    name: "Entryway Furniture",
    category: "Furniture",
  },
  {
    value: "bathroom_furniture",
    name: "Bathroom Furniture",
    category: "Furniture",
  },
  {
    value: "game_room_furniture",
    name: "Game Room Furniture",
    category: "Furniture",
  },
  { value: "futons", name: "Futons", category: "Furniture" },

  // Mobiles & Tablets
  { value: "mobiles & tablets", name: "Mobiles & Tablets" },
  { value: "smartphones", name: "Smartphones", category: "Mobiles & Tablets" },
  { value: "tablets", name: "Tablets", category: "Mobiles & Tablets" },
  {
    value: "smartphone_accessories",
    name: "Smartphone Accessories",
    category: "Mobiles & Tablets",
  },
  {
    value: "tablet_accessories",
    name: "Tablet Accessories",
    category: "Mobiles & Tablets",
  },
  {
    value: "wearable_tech",
    name: "Wearable Tech",
    category: "Mobiles & Tablets",
  },
  {
    value: "mobile_covers",
    name: "Mobile Covers",
    category: "Mobiles & Tablets",
  },
  {
    value: "screen_protectors",
    name: "Screen Protectors",
    category: "Mobiles & Tablets",
  },
  {
    value: "chargers_and_cables",
    name: "Chargers & Cables",
    category: "Mobiles & Tablets",
  },
  {
    value: "tablet_covers",
    name: "Tablet Covers",
    category: "Mobiles & Tablets",
  },
  { value: "power_banks", name: "Power Banks", category: "Mobiles & Tablets" },
  {
    value: "smartwatch_accessories",
    name: "Smartwatch Accessories",
    category: "Mobiles & Tablets",
  },
  {
    value: "phone_earbuds",
    name: "Phone Earbuds",
    category: "Mobiles & Tablets",
  },
  {
    value: "bluetooth_headsets",
    name: "Bluetooth Headsets",
    category: "Mobiles & Tablets",
  },
  {
    value: "mobile_stands",
    name: "Mobile Stands",
    category: "Mobiles & Tablets",
  },
  {
    value: "tablet_stands",
    name: "Tablet Stands",
    category: "Mobiles & Tablets",
  },
  {
    value: "phone_cameras",
    name: "Phone Cameras",
    category: "Mobiles & Tablets",
  },
  {
    value: "tablet_cameras",
    name: "Tablet Cameras",
    category: "Mobiles & Tablets",
  },
  {
    value: "charging_stations",
    name: "Charging Stations",
    category: "Mobiles & Tablets",
  },
  {
    value: "smartphone_repair_kits",
    name: "Smartphone Repair Kits",
    category: "Mobiles & Tablets",
  },

  // Home & Kitchen
  { value: "home & kitchen", name: "Home & Kitchen" },
  {
    value: "kitchen_appliances",
    name: "Kitchen Appliances",
    category: "Home & Kitchen",
  },
  { value: "cookware", name: "Cookware", category: "Home & Kitchen" },
  { value: "bedding", name: "Bedding", category: "Home & Kitchen" },
  { value: "furniture", name: "Furniture", category: "Home & Kitchen" },
  { value: "home_decor", name: "Home Decor", category: "Home & Kitchen" },
  {
    value: "cleaning_supplies",
    name: "Cleaning Supplies",
    category: "Home & Kitchen",
  },
  {
    value: "storage_solutions",
    name: "Storage Solutions",
    category: "Home & Kitchen",
  },
  {
    value: "small_appliances",
    name: "Small Appliances",
    category: "Home & Kitchen",
  },
  {
    value: "kitchen_storage",
    name: "Kitchen Storage",
    category: "Home & Kitchen",
  },
  {
    value: "bathroom_accessories",
    name: "Bathroom Accessories",
    category: "Home & Kitchen",
  },
  {
    value: "vacuum_cleaners",
    name: "Vacuum Cleaners",
    category: "Home & Kitchen",
  },
  {
    value: "air_conditioners",
    name: "Air Conditioners",
    category: "Home & Kitchen",
  },
  { value: "heaters", name: "Heaters", category: "Home & Kitchen" },
  { value: "blenders", name: "Blenders", category: "Home & Kitchen" },
  { value: "coffee_makers", name: "Coffee Makers", category: "Home & Kitchen" },
  { value: "microwaves", name: "Microwaves", category: "Home & Kitchen" },
  { value: "dishwashers", name: "Dishwashers", category: "Home & Kitchen" },
  { value: "refrigerators", name: "Refrigerators", category: "Home & Kitchen" },
  {
    value: "washing_machines",
    name: "Washing Machines",
    category: "Home & Kitchen",
  },
  { value: "irons", name: "Irons", category: "Home & Kitchen" },

  // Other
  { value: "other", name: "Other" },
  { value: "sports", name: "Sports", category: "Other" },
  { value: "automotive", name: "Automotive", category: "Other" },
  { value: "books", name: "Books", category: "Other" },
  { value: "music", name: "Music", category: "Other" },
  { value: "movies", name: "Movies", category: "Other" },
  { value: "toys", name: "Toys", category: "Other" },
  { value: "pet_supplies", name: "Pet Supplies", category: "Other" },
  { value: "health", name: "Health", category: "Other" },
  { value: "office_supplies", name: "Office Supplies", category: "Other" },
  { value: "outdoor", name: "Outdoor", category: "Other" },
  { value: "crafts", name: "Crafts", category: "Other" },
  { value: "garden", name: "Garden", category: "Other" },
  { value: "travel", name: "Travel", category: "Other" },
  { value: "fitness", name: "Fitness", category: "Other" },
  { value: "baby_products", name: "Baby Products", category: "Other" },
  { value: "hobbies", name: "Hobbies", category: "Other" },
  {
    value: "musical_instruments",
    name: "Musical Instruments",
    category: "Other",
  },
  { value: "collectibles", name: "Collectibles", category: "Other" },
  { value: "party_supplies", name: "Party Supplies", category: "Other" },
  { value: "home_improvement", name: "Home Improvement", category: "Other" },
  { value: "healthcare", name: "Healthcare", category: "Other" },
  { value: "jigsaw_puzzles", name: "Jigsaw Puzzles", category: "Other" },
  { value: "board_games", name: "Board Games", category: "Other" },
  { value: "fitness_equipment", name: "Fitness Equipment", category: "Other" },
  { value: "camping", name: "Camping", category: "Other" },
  { value: "cycling", name: "Cycling", category: "Other" },
  { value: "skateboarding", name: "Skateboarding", category: "Other" },
  { value: "climbing", name: "Climbing", category: "Other" },
  { value: "hiking", name: "Hiking", category: "Other" },
  { value: "fishing", name: "Fishing", category: "Other" },
  { value: "water_sports", name: "Water Sports", category: "Other" },
  { value: "skiing", name: "Skiing", category: "Other" },
  { value: "snowboarding", name: "Snowboarding", category: "Other" },
  { value: "surfing", name: "Surfing", category: "Other" },
  { value: "winter_sports", name: "Winter Sports", category: "Other" },
  { value: "summer_sports", name: "Summer Sports", category: "Other" },
  { value: "personal_safety", name: "Personal Safety", category: "Other" },
  {
    value: "emergency_supplies",
    name: "Emergency Supplies",
    category: "Other",
  },
  { value: "tactical_gear", name: "Tactical Gear", category: "Other" },
  { value: "survival_gear", name: "Survival Gear", category: "Other" },
  { value: "first_aid", name: "First Aid", category: "Other" },
  { value: "clothing", name: "Clothing", category: "Other" },
];

export const targetPeople = [
  { for: "Tech Enthusiasts", name: "Tech Enthusiasts" },
  { for: "Fitness Enthusiasts", name: "Fitness Enthusiasts" },
  { for: "Music Lovers", name: "Music Lovers" },
  { for: "Bookworms", name: "Bookworms" },
  { for: "Gamers", name: "Gamers" },
  { for: "Foodies", name: "Foodies" },
  { for: "Outdoor Adventurers", name: "Outdoor Adventurers" },
  { for: "Fashionistas", name: "Fashionistas" },
  { for: "Art Aficionados", name: "Art Aficionados" },
  { for: "Pet Lovers", name: "Pet Lovers" },
  { for: "Travel Enthusiasts", name: "Travel Enthusiasts" },
  { for: "Movie Buffs", name: "Movie Buffs" },
  { for: "Yoga Practitioners", name: "Yoga Practitioners" },
  { for: "Photography Enthusiasts", name: "Photography Enthusiasts" },
  { for: "DIY Enthusiasts", name: "DIY Enthusiasts" },
  { for: "Gardening Enthusiasts", name: "Gardening Enthusiasts" },
  { for: "History Buffs", name: "History Buffs" },
  { for: "Health and Wellness Seekers", name: "Health and Wellness Seekers" },
  { for: "Craft Beer Enthusiasts", name: "Craft Beer Enthusiasts" },
  { for: "Environmental Activists", name: "Environmental Activists" },
  { for: "Animal Rights Advocates", name: "Animal Rights Advocates" },
  { for: "Entrepreneurs", name: "Entrepreneurs" },
  { for: "Home Chefs", name: "Home Chefs" },
  { for: "Musicians", name: "Musicians" },
  { for: "Fitness Instructors", name: "Fitness Instructors" },
  { for: "Digital Nomads", name: "Digital Nomads" },
  { for: "Language Learners", name: "Language Learners" },
  { for: "Sustainability Advocates", name: "Sustainability Advocates" },
  { for: "Social Media Influencers", name: "Social Media Influencers" },
  {
    for: "Artificial Intelligence Enthusiasts",
    name: "Artificial Intelligence Enthusiasts",
  },
  { for: "Beauty Enthusiasts", name: "Beauty Enthusiasts" },
  { for: "Astronomy Enthusiasts", name: "Astronomy Enthusiasts" },
  { for: "Volunteers", name: "Volunteers" },
  { for: "Tea Connoisseurs", name: "Tea Connoisseurs" },
  { for: "Coffee Lovers", name: "Coffee Lovers" },
  { for: "Comic Book Fans", name: "Comic Book Fans" },
  { for: "Board Game Enthusiasts", name: "Board Game Enthusiasts" },
  { for: "Interior Design Enthusiasts", name: "Interior Design Enthusiasts" },
  { for: "Thrill Seekers", name: "Thrill Seekers" },
  { for: "Concertgoers", name: "Concertgoers" },
  { for: "Eco-Tourists", name: "Eco-Tourists" },
  { for: "Vintage Collectors", name: "Vintage Collectors" },
  { for: "Sneakerheads", name: "Sneakerheads" },
  { for: "Fitness Freaks", name: "Fitness Freaks" },
  { for: "Podcast Listeners", name: "Podcast Listeners" },
  { for: "Street Food Enthusiasts", name: "Street Food Enthusiasts" },
  { for: "Mountain Climbers", name: "Mountain Climbers" },
  { for: "Fashion Bloggers", name: "Fashion Bloggers" },
  { for: "History Enthusiasts", name: "History Enthusiasts" },
  { for: "Soccer Fans", name: "Soccer Fans" },
  { for: "Basketball Fans", name: "Basketball Fans" },
  { for: "Cyclists", name: "Cyclists" },
  { for: "Surfers", name: "Surfers" },
  { for: "Skateboarders", name: "Skateboarders" },
  { for: "Art Collectors", name: "Art Collectors" },
  { for: "Rock Climbers", name: "Rock Climbers" },
  { for: "Tech Start-Up Enthusiasts", name: "Tech Start-Up Enthusiasts" },
  { for: "Vegetarian/Vegan Advocates", name: "Vegetarian/Vegan Advocates" },
  { for: "Astrophotographers", name: "Astrophotographers" },
  { for: "Birdwatchers", name: "Birdwatchers" },
  { for: "Meditation Practitioners", name: "Meditation Practitioners" },
  { for: "Food Bloggers", name: "Food Bloggers" },
  { for: "Fashion Designers", name: "Fashion Designers" },
  { for: "Fitness Models", name: "Fitness Models" },
  { for: "Travel Bloggers", name: "Travel Bloggers" },
  { for: "Digital Artists", name: "Digital Artists" },
  { for: "VR Enthusiasts", name: "VR Enthusiasts" },
  { for: "Science Fiction Fans", name: "Science Fiction Fans" },
  { for: "Documentary Buffs", name: "Documentary Buffs" },
  { for: "Wine Connoisseurs", name: "Wine Connoisseurs" },
  { for: "Whiskey Aficionados", name: "Whiskey Aficionados" },
  { for: "Gin Enthusiasts", name: "Gin Enthusiasts" },
  { for: "Rum Connoisseurs", name: "Rum Connoisseurs" },
  { for: "Whale Watching Enthusiasts", name: "Whale Watching Enthusiasts" },
  { for: "Paddleboarders", name: "Paddleboarders" },
  { for: "Kite Surfers", name: "Kite Surfers" },
  { for: "Salsa Dancers", name: "Salsa Dancers" },
  { for: "Jazz Aficionados", name: "Jazz Aficionados" },
  { for: "Scuba Divers", name: "Scuba Divers" },
  { for: "Snorkelers", name: "Snorkelers" },
  { for: "Fine Dining Enthusiasts", name: "Fine Dining Enthusiasts" },
  { for: "Culinary Adventurers", name: "Culinary Adventurers" },
  { for: "Food Truck Fans", name: "Food Truck Fans" },
  { for: "Kombucha Enthusiasts", name: "Kombucha Enthusiasts" },
  { for: "Eco-Friendly Shoppers", name: "Eco-Friendly Shoppers" },
  { for: "Zero Waste Advocates", name: "Zero Waste Advocates" },
  { for: "Minimalists", name: "Minimalists" },
  { for: "Naturalists", name: "Naturalists" },
  { for: "Camping Enthusiasts", name: "Camping Enthusiasts" },
  { for: "Extreme Sports Enthusiasts", name: "Extreme Sports Enthusiasts" },
  { for: "Parkour Practitioners", name: "Parkour Practitioners" },
  { for: "Pottery Enthusiasts", name: "Pottery Enthusiasts" },
  { for: "Antique Collectors", name: "Antique Collectors" },
  { for: "Retro Gaming Enthusiasts", name: "Retro Gaming Enthusiasts" },
  { for: "Bonsai Enthusiasts", name: "Bonsai Enthusiasts" },
  { for: "Model Train Enthusiasts", name: "Model Train Enthusiasts" },
  {
    for: "Aerial Photography Enthusiasts",
    name: "Aerial Photography Enthusiasts",
  },
  { for: "Urban Explorers", name: "Urban Explorers" },
];

export const countryFilter = [
  {
    country: "Afghanistan",
    shortname: "AF",
    countryCode: "+93",
    currency: "Afghani",
    symbol: "؋",
  },
  {
    country: "Albania",
    shortname: "AL",
    countryCode: "+355",
    currency: "Lek",
    symbol: "L",
  },
  {
    country: "Algeria",
    shortname: "DZ",
    countryCode: "+213",
    currency: "Dinar",
    symbol: "د.ج",
  },
  {
    country: "Andorra",
    shortname: "AD",
    countryCode: "+376",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Angola",
    shortname: "AO",
    countryCode: "+244",
    currency: "Kwanza",
    symbol: "Kz",
  },
  {
    country: "Antigua and Barbuda",
    shortname: "AG",
    countryCode: "+1-268",
    currency: "East Caribbean Dollar",
    symbol: "$",
  },
  {
    country: "Argentina",
    shortname: "AR",
    countryCode: "+54",
    currency: "Peso",
    symbol: "$",
  },
  {
    country: "Armenia",
    shortname: "AM",
    countryCode: "+374",
    currency: "Dram",
    symbol: "֏",
  },
  {
    country: "Australia",
    shortname: "AU",
    countryCode: "+61",
    currency: "Australian Dollar",
    symbol: "$",
  },
  {
    country: "Austria",
    shortname: "AT",
    countryCode: "+43",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Azerbaijan",
    shortname: "AZ",
    countryCode: "+994",
    currency: "Manat",
    symbol: "₼",
  },
  {
    country: "Bahamas",
    shortname: "BS",
    countryCode: "+1-242",
    currency: "Bahamian Dollar",
    symbol: "$",
  },
  {
    country: "Bahrain",
    shortname: "BH",
    countryCode: "+973",
    currency: "Dinar",
    symbol: ".د.ب",
  },
  {
    country: "Bangladesh",
    shortname: "BD",
    countryCode: "+880",
    currency: "Taka",
    symbol: "৳",
  },
  {
    country: "Barbados",
    shortname: "BB",
    countryCode: "+1-246",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Belarus",
    shortname: "BY",
    countryCode: "+375",
    currency: "Belarusian Ruble",
    symbol: "Br",
  },
  {
    country: "Belgium",
    shortname: "BE",
    countryCode: "+32",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Belize",
    shortname: "BZ",
    countryCode: "+501",
    currency: "Belize Dollar",
    symbol: "$",
  },
  {
    country: "Benin",
    shortname: "BJ",
    countryCode: "+229",
    currency: "West African CFA Franc",
    symbol: "CFA",
  },
  {
    country: "Bhutan",
    shortname: "BT",
    countryCode: "+975",
    currency: "Ngultrum",
    symbol: "Nu.",
  },
  {
    country: "Bolivia",
    shortname: "BO",
    countryCode: "+591",
    currency: "Boliviano",
    symbol: "Bs.",
  },
  {
    country: "Bosnia and Herzegovina",
    shortname: "BA",
    countryCode: "+387",
    currency: "Convertible Mark",
    symbol: "KM",
  },
  {
    country: "Botswana",
    shortname: "BW",
    countryCode: "+267",
    currency: "Pula",
    symbol: "P",
  },
  {
    country: "Brazil",
    shortname: "BR",
    countryCode: "+55",
    currency: "Real",
    symbol: "R$",
  },
  {
    country: "Brunei",
    shortname: "BN",
    countryCode: "+673",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Bulgaria",
    shortname: "BG",
    countryCode: "+359",
    currency: "Lev",
    symbol: "лв",
  },
  {
    country: "Burkina Faso",
    shortname: "BF",
    countryCode: "+226",
    currency: "West African CFA Franc",
    symbol: "CFA",
  },
  {
    country: "Burundi",
    shortname: "BI",
    countryCode: "+257",
    currency: "Burundi Franc",
    symbol: "FBu",
  },
  {
    country: "Cabo Verde",
    shortname: "CV",
    countryCode: "+238",
    currency: "Escudo",
    symbol: "$",
  },
  {
    country: "Cambodia",
    shortname: "KH",
    countryCode: "+855",
    currency: "Riel",
    symbol: "៛",
  },
  {
    country: "Cameroon",
    shortname: "CM",
    countryCode: "+237",
    currency: "Central African CFA Franc",
    symbol: "FCFA",
  },
  {
    country: "Canada",
    shortname: "CA",
    countryCode: "+1",
    currency: "Canadian Dollar",
    symbol: "$",
  },
  {
    country: "Central African Republic",
    shortname: "CF",
    countryCode: "+236",
    currency: "Central African CFA Franc",
    symbol: "FCFA",
  },
  {
    country: "Chad",
    shortname: "TD",
    countryCode: "+235",
    currency: "Central African CFA Franc",
    symbol: "FCFA",
  },
  {
    country: "Chile",
    shortname: "CL",
    countryCode: "+56",
    currency: "Peso",
    symbol: "$",
  },
  {
    country: "China",
    shortname: "CN",
    countryCode: "+86",
    currency: "Yuan Renminbi",
    symbol: "¥",
  },
  {
    country: "Colombia",
    shortname: "CO",
    countryCode: "+57",
    currency: "Peso",
    symbol: "$",
  },
  {
    country: "Comoros",
    shortname: "KM",
    countryCode: "+269",
    currency: "Franc",
    symbol: "CF",
  },
  {
    country: "Congo, Democratic Republic of the",
    shortname: "CD",
    countryCode: "+243",
    currency: "Congolese Franc",
    symbol: "FC",
  },
  {
    country: "Congo, Republic of the",
    shortname: "CG",
    countryCode: "+242",
    currency: "Central African CFA Franc",
    symbol: "FCFA",
  },
  {
    country: "Costa Rica",
    shortname: "CR",
    countryCode: "+506",
    currency: "Colón",
    symbol: "₡",
  },
  {
    country: "Croatia",
    shortname: "HR",
    countryCode: "+385",
    currency: "Kuna",
    symbol: "kn",
  },
  {
    country: "Cuba",
    shortname: "CU",
    countryCode: "+53",
    currency: "Cuban Peso",
    symbol: "$",
  },
  {
    country: "Cyprus",
    shortname: "CY",
    countryCode: "+357",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Czech Republic",
    shortname: "CZ",
    countryCode: "+420",
    currency: "Koruna",
    symbol: "Kč",
  },
  {
    country: "Denmark",
    shortname: "DK",
    countryCode: "+45",
    currency: "Krone",
    symbol: "kr",
  },
  {
    country: "Djibouti",
    shortname: "DJ",
    countryCode: "+253",
    currency: "Djiboutian Franc",
    symbol: "Fdj",
  },
  {
    country: "Dominica",
    shortname: "DM",
    countryCode: "+1-767",
    currency: "East Caribbean Dollar",
    symbol: "$",
  },
  {
    country: "Dominican Republic",
    shortname: "DO",
    countryCode: "+1-809",
    currency: "Peso",
    symbol: "RD$",
  },
  {
    country: "East Timor",
    shortname: "TL",
    countryCode: "+670",
    currency: "United States Dollar",
    symbol: "$",
  },
  {
    country: "Ecuador",
    shortname: "EC",
    countryCode: "+593",
    currency: "United States Dollar",
    symbol: "$",
  },
  {
    country: "Egypt",
    shortname: "EG",
    countryCode: "+20",
    currency: "Egyptian Pound",
    symbol: "£",
  },
  {
    country: "El Salvador",
    shortname: "SV",
    countryCode: "+503",
    currency: "United States Dollar",
    symbol: "$",
  },
  {
    country: "Equatorial Guinea",
    shortname: "GQ",
    countryCode: "+240",
    currency: "Central African CFA Franc",
    symbol: "FCFA",
  },
  {
    country: "Eritrea",
    shortname: "ER",
    countryCode: "+291",
    currency: "Nakfa",
    symbol: "Nkf",
  },
  {
    country: "Estonia",
    shortname: "EE",
    countryCode: "+372",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Eswatini",
    shortname: "SZ",
    countryCode: "+268",
    currency: "Lilangeni",
    symbol: "L",
  },
  {
    country: "Ethiopia",
    shortname: "ET",
    countryCode: "+251",
    currency: "Birr",
    symbol: "Br",
  },
  {
    country: "Fiji",
    shortname: "FJ",
    countryCode: "+679",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Finland",
    shortname: "FI",
    countryCode: "+358",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "France",
    shortname: "FR",
    countryCode: "+33",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Gabon",
    shortname: "GA",
    countryCode: "+241",
    currency: "Central African CFA Franc",
    symbol: "FCFA",
  },
  {
    country: "Gambia",
    shortname: "GM",
    countryCode: "+220",
    currency: "Dalasi",
    symbol: "D",
  },
  {
    country: "Georgia",
    shortname: "GE",
    countryCode: "+995",
    currency: "Lari",
    symbol: "₾",
  },
  {
    country: "Germany",
    shortname: "DE",
    countryCode: "+49",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Ghana",
    shortname: "GH",
    countryCode: "+233",
    currency: "Cedi",
    symbol: "₵",
  },
  {
    country: "Greece",
    shortname: "GR",
    countryCode: "+30",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Grenada",
    shortname: "GD",
    countryCode: "+1-473",
    currency: "East Caribbean Dollar",
    symbol: "$",
  },
  {
    country: "Guatemala",
    shortname: "GT",
    countryCode: "+502",
    currency: "Quetzal",
    symbol: "Q",
  },
  {
    country: "Guinea",
    shortname: "GN",
    countryCode: "+224",
    currency: "Guinean Franc",
    symbol: "FG",
  },
  {
    country: "Guinea-Bissau",
    shortname: "GW",
    countryCode: "+245",
    currency: "West African CFA Franc",
    symbol: "CFA",
  },
  {
    country: "Guyana",
    shortname: "GY",
    countryCode: "+592",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Haiti",
    shortname: "HT",
    countryCode: "+509",
    currency: "Gourde",
    symbol: "G",
  },
  {
    country: "Honduras",
    shortname: "HN",
    countryCode: "+504",
    currency: "Lempira",
    symbol: "L",
  },
  {
    country: "Hungary",
    shortname: "HU",
    countryCode: "+36",
    currency: "Forint",
    symbol: "Ft",
  },
  {
    country: "Iceland",
    shortname: "IS",
    countryCode: "+354",
    currency: "Icelandic Króna",
    symbol: "kr",
  },
  {
    country: "India",
    shortname: "IN",
    countryCode: "+91",
    currency: "Rupee",
    symbol: "₹",
  },
  {
    country: "Indonesia",
    shortname: "ID",
    countryCode: "+62",
    currency: "Rupiah",
    symbol: "Rp",
  },
  {
    country: "Iran",
    shortname: "IR",
    countryCode: "+98",
    currency: "Rial",
    symbol: "﷼",
  },
  {
    country: "Iraq",
    shortname: "IQ",
    countryCode: "+964",
    currency: "Dinar",
    symbol: "ع.د",
  },
  {
    country: "Ireland",
    shortname: "IE",
    countryCode: "+353",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Israel",
    shortname: "IL",
    countryCode: "+972",
    currency: "Shekel",
    symbol: "₪",
  },
  {
    country: "Italy",
    shortname: "IT",
    countryCode: "+39",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Jamaica",
    shortname: "JM",
    countryCode: "+1-876",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Japan",
    shortname: "JP",
    countryCode: "+81",
    currency: "Yen",
    symbol: "¥",
  },
  {
    country: "Jordan",
    shortname: "JO",
    countryCode: "+962",
    currency: "Dinar",
    symbol: "د.ا",
  },
  {
    country: "Kazakhstan",
    shortname: "KZ",
    countryCode: "+7",
    currency: "Tenge",
    symbol: "₸",
  },
  {
    country: "Kenya",
    shortname: "KE",
    countryCode: "+254",
    currency: "Shilling",
    symbol: "Sh",
  },
  {
    country: "Kiribati",
    shortname: "KI",
    countryCode: "+686",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Kuwait",
    shortname: "KW",
    countryCode: "+965",
    currency: "Dinar",
    symbol: "د.ك",
  },
  {
    country: "Kyrgyzstan",
    shortname: "KG",
    countryCode: "+996",
    currency: "Som",
    symbol: "с",
  },
  {
    country: "Laos",
    shortname: "LA",
    countryCode: "+856",
    currency: "Kip",
    symbol: "₭",
  },
  {
    country: "Latvia",
    shortname: "LV",
    countryCode: "+371",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Lebanon",
    shortname: "LB",
    countryCode: "+961",
    currency: "Pound",
    symbol: "ل.ل",
  },
  {
    country: "Lesotho",
    shortname: "LS",
    countryCode: "+266",
    currency: "Loti",
    symbol: "L",
  },
  {
    country: "Liberia",
    shortname: "LR",
    countryCode: "+231",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Libya",
    shortname: "LY",
    countryCode: "+218",
    currency: "Dinar",
    symbol: "ل.د",
  },
  {
    country: "Liechtenstein",
    shortname: "LI",
    countryCode: "+423",
    currency: "Swiss Franc",
    symbol: "Fr",
  },
  {
    country: "Lithuania",
    shortname: "LT",
    countryCode: "+370",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Luxembourg",
    shortname: "LU",
    countryCode: "+352",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Madagascar",
    shortname: "MG",
    countryCode: "+261",
    currency: "Ariary",
    symbol: "Ar",
  },
  {
    country: "Malawi",
    shortname: "MW",
    countryCode: "+265",
    currency: "Kwacha",
    symbol: "MK",
  },
  {
    country: "Malaysia",
    shortname: "MY",
    countryCode: "+60",
    currency: "Ringgit",
    symbol: "RM",
  },
  {
    country: "Maldives",
    shortname: "MV",
    countryCode: "+960",
    currency: "Rufiyaa",
    symbol: "Rf",
  },
  {
    country: "Mali",
    shortname: "ML",
    countryCode: "+223",
    currency: "West African CFA Franc",
    symbol: "CFA",
  },
  {
    country: "Malta",
    shortname: "MT",
    countryCode: "+356",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Marshall Islands",
    shortname: "MH",
    countryCode: "+692",
    currency: "United States Dollar",
    symbol: "$",
  },
  {
    country: "Mauritania",
    shortname: "MR",
    countryCode: "+222",
    currency: "Ouguiya",
    symbol: "UM",
  },
  {
    country: "Mauritius",
    shortname: "MU",
    countryCode: "+230",
    currency: "Rupee",
    symbol: "₨",
  },
  {
    country: "Mexico",
    shortname: "MX",
    countryCode: "+52",
    currency: "Peso",
    symbol: "$",
  },
  {
    country: "Micronesia",
    shortname: "FM",
    countryCode: "+691",
    currency: "United States Dollar",
    symbol: "$",
  },
  {
    country: "Moldova",
    shortname: "MD",
    countryCode: "+373",
    currency: "Leu",
    symbol: "L",
  },
  {
    country: "Monaco",
    shortname: "MC",
    countryCode: "+377",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Mongolia",
    shortname: "MN",
    countryCode: "+976",
    currency: "Tugrik",
    symbol: "₮",
  },
  {
    country: "Montenegro",
    shortname: "ME",
    countryCode: "+382",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Morocco",
    shortname: "MA",
    countryCode: "+212",
    currency: "Dirham",
    symbol: "د.م.",
  },
  {
    country: "Mozambique",
    shortname: "MZ",
    countryCode: "+258",
    currency: "Metical",
    symbol: "MT",
  },
  {
    country: "Myanmar",
    shortname: "MM",
    countryCode: "+95",
    currency: "Kyat",
    symbol: "K",
  },
  {
    country: "Namibia",
    shortname: "NA",
    countryCode: "+264",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Nauru",
    shortname: "NR",
    countryCode: "+674",
    currency: "Australian Dollar",
    symbol: "$",
  },
  {
    country: "Nepal",
    shortname: "NP",
    countryCode: "+977",
    currency: "Rupee",
    symbol: "₨",
  },
  {
    country: "Netherlands",
    shortname: "NL",
    countryCode: "+31",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "New Zealand",
    shortname: "NZ",
    countryCode: "+64",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Nicaragua",
    shortname: "NI",
    countryCode: "+505",
    currency: "Córdoba",
    symbol: "C$",
  },
  {
    country: "Niger",
    shortname: "NE",
    countryCode: "+227",
    currency: "West African CFA Franc",
    symbol: "CFA",
  },
  {
    country: "Nigeria",
    shortname: "NG",
    countryCode: "+234",
    currency: "Naira",
    symbol: "₦",
  },
  {
    country: "North Korea",
    shortname: "KP",
    countryCode: "+850",
    currency: "Won",
    symbol: "₩",
  },
  {
    country: "North Macedonia",
    shortname: "MK",
    countryCode: "+389",
    currency: "Denar",
    symbol: "ден",
  },
  {
    country: "Norway",
    shortname: "NO",
    countryCode: "+47",
    currency: "Krone",
    symbol: "kr",
  },
  {
    country: "Oman",
    shortname: "OM",
    countryCode: "+968",
    currency: "Rial",
    symbol: "ر.ع.",
  },
  {
    country: "Pakistan",
    shortname: "PK",
    countryCode: "+92",
    currency: "Rupee",
    symbol: "₨",
  },
  {
    country: "Palau",
    shortname: "PW",
    countryCode: "+680",
    currency: "United States Dollar",
    symbol: "$",
  },
  {
    country: "Panama",
    shortname: "PA",
    countryCode: "+507",
    currency: "Balboa",
    symbol: "B/.",
  },
  {
    country: "Papua New Guinea",
    shortname: "PG",
    countryCode: "+675",
    currency: "Kina",
    symbol: "K",
  },
  {
    country: "Paraguay",
    shortname: "PY",
    countryCode: "+595",
    currency: "Guarani",
    symbol: "₲",
  },
  {
    country: "Peru",
    shortname: "PE",
    countryCode: "+51",
    currency: "Sol",
    symbol: "S/",
  },
  {
    country: "Philippines",
    shortname: "PH",
    countryCode: "+63",
    currency: "Peso",
    symbol: "₱",
  },
  {
    country: "Poland",
    shortname: "PL",
    countryCode: "+48",
    currency: "Zloty",
    symbol: "zł",
  },
  {
    country: "Portugal",
    shortname: "PT",
    countryCode: "+351",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Qatar",
    shortname: "QA",
    countryCode: "+974",
    currency: "Riyal",
    symbol: "ر.ق",
  },
  {
    country: "Romania",
    shortname: "RO",
    countryCode: "+40",
    currency: "Leu",
    symbol: "lei",
  },
  {
    country: "Russia",
    shortname: "RU",
    countryCode: "+7",
    currency: "Ruble",
    symbol: "₽",
  },
  {
    country: "Rwanda",
    shortname: "RW",
    countryCode: "+250",
    currency: "Franc",
    symbol: "FRw",
  },
  {
    country: "Saint Kitts and Nevis",
    shortname: "KN",
    countryCode: "+1-869",
    currency: "East Caribbean Dollar",
    symbol: "$",
  },
  {
    country: "Saint Lucia",
    shortname: "LC",
    countryCode: "+1-758",
    currency: "East Caribbean Dollar",
    symbol: "$",
  },
  {
    country: "Saint Vincent and the Grenadines",
    shortname: "VC",
    countryCode: "+1-784",
    currency: "East Caribbean Dollar",
    symbol: "$",
  },
  {
    country: "Samoa",
    shortname: "WS",
    countryCode: "+685",
    currency: "Tala",
    symbol: "T",
  },
  {
    country: "San Marino",
    shortname: "SM",
    countryCode: "+378",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Sao Tome and Principe",
    shortname: "ST",
    countryCode: "+239",
    currency: "Dobra",
    symbol: "Db",
  },
  {
    country: "Saudi Arabia",
    shortname: "SA",
    countryCode: "+966",
    currency: "Riyal",
    symbol: "ر.س",
  },
  {
    country: "Senegal",
    shortname: "SN",
    countryCode: "+221",
    currency: "West African CFA Franc",
    symbol: "CFA",
  },
  {
    country: "Serbia",
    shortname: "RS",
    countryCode: "+381",
    currency: "Dinar",
    symbol: "дин",
  },
  {
    country: "Seychelles",
    shortname: "SC",
    countryCode: "+248",
    currency: "Rupee",
    symbol: "₨",
  },
  {
    country: "Sierra Leone",
    shortname: "SL",
    countryCode: "+232",
    currency: "Leone",
    symbol: "Le",
  },
  {
    country: "Singapore",
    shortname: "SG",
    countryCode: "+65",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Slovakia",
    shortname: "SK",
    countryCode: "+421",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Slovenia",
    shortname: "SI",
    countryCode: "+386",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Solomon Islands",
    shortname: "SB",
    countryCode: "+677",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Somalia",
    shortname: "SO",
    countryCode: "+252",
    currency: "Shilling",
    symbol: "Sh",
  },
  {
    country: "South Africa",
    shortname: "ZA",
    countryCode: "+27",
    currency: "Rand",
    symbol: "R",
  },
  {
    country: "South Korea",
    shortname: "KR",
    countryCode: "+82",
    currency: "Won",
    symbol: "₩",
  },
  {
    country: "South Sudan",
    shortname: "SS",
    countryCode: "+211",
    currency: "Pound",
    symbol: "£",
  },
  {
    country: "Spain",
    shortname: "ES",
    countryCode: "+34",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Sri Lanka",
    shortname: "LK",
    countryCode: "+94",
    currency: "Rupee",
    symbol: "₨",
  },
  {
    country: "Sudan",
    shortname: "SD",
    countryCode: "+249",
    currency: "Pound",
    symbol: "ج.س.",
  },
  {
    country: "Suriname",
    shortname: "SR",
    countryCode: "+597",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Sweden",
    shortname: "SE",
    countryCode: "+46",
    currency: "Krona",
    symbol: "kr",
  },
  {
    country: "Switzerland",
    shortname: "CH",
    countryCode: "+41",
    currency: "Swiss Franc",
    symbol: "Fr",
  },
  {
    country: "Syria",
    shortname: "SY",
    countryCode: "+963",
    currency: "Pound",
    symbol: "£",
  },
  {
    country: "Taiwan",
    shortname: "TW",
    countryCode: "+886",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Tajikistan",
    shortname: "TJ",
    countryCode: "+992",
    currency: "Somoni",
    symbol: "ЅМ",
  },
  {
    country: "Tanzania",
    shortname: "TZ",
    countryCode: "+255",
    currency: "Shilling",
    symbol: "Sh",
  },
  {
    country: "Thailand",
    shortname: "TH",
    countryCode: "+66",
    currency: "Baht",
    symbol: "฿",
  },
  {
    country: "Togo",
    shortname: "TG",
    countryCode: "+228",
    currency: "West African CFA Franc",
    symbol: "CFA",
  },
  {
    country: "Tonga",
    shortname: "TO",
    countryCode: "+676",
    currency: "Pa'anga",
    symbol: "T$",
  },
  {
    country: "Trinidad and Tobago",
    shortname: "TT",
    countryCode: "+1-868",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Tunisia",
    shortname: "TN",
    countryCode: "+216",
    currency: "Dinar",
    symbol: "د.ت",
  },
  {
    country: "Turkey",
    shortname: "TR",
    countryCode: "+90",
    currency: "Lira",
    symbol: "₺",
  },
  {
    country: "Turkmenistan",
    shortname: "TM",
    countryCode: "+993",
    currency: "Manat",
    symbol: "m",
  },
  {
    country: "Tuvalu",
    shortname: "TV",
    countryCode: "+688",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Uganda",
    shortname: "UG",
    countryCode: "+256",
    currency: "Shilling",
    symbol: "Sh",
  },
  {
    country: "Ukraine",
    shortname: "UA",
    countryCode: "+380",
    currency: "Hryvnia",
    symbol: "₴",
  },
  {
    country: "United Arab Emirates",
    shortname: "AE",
    countryCode: "+971",
    currency: "Dirham",
    symbol: "د.إ",
  },
  {
    country: "United Kingdom",
    shortname: "GB",
    countryCode: "+44",
    currency: "Pound",
    symbol: "£",
  },
  {
    country: "United States",
    shortname: "US",
    countryCode: "+1",
    currency: "Dollar",
    symbol: "$",
  },
  {
    country: "Uruguay",
    shortname: "UY",
    countryCode: "+598",
    currency: "Peso",
    symbol: "$",
  },
  {
    country: "Uzbekistan",
    shortname: "UZ",
    countryCode: "+998",
    currency: "Som",
    symbol: "soʻm",
  },
  {
    country: "Vanuatu",
    shortname: "VU",
    countryCode: "+678",
    currency: "Vatu",
    symbol: "VT",
  },
  {
    country: "Vatican City",
    shortname: "VA",
    countryCode: "+379",
    currency: "Euro",
    symbol: "€",
  },
  {
    country: "Venezuela",
    shortname: "VE",
    countryCode: "+58",
    currency: "Bolívar",
    symbol: "Bs.S",
  },
  {
    country: "Vietnam",
    shortname: "VN",
    countryCode: "+84",
    currency: "Dong",
    symbol: "₫",
  },
  {
    country: "Yemen",
    shortname: "YE",
    countryCode: "+967",
    currency: "Rial",
    symbol: "﷼",
  },
  {
    country: "Zambia",
    shortname: "ZM",
    countryCode: "+260",
    currency: "Kwacha",
    symbol: "ZK",
  },
  {
    country: "Zimbabwe",
    shortname: "ZW",
    countryCode: "+263",
    currency: "Dollar",
    symbol: "$",
  },
];

export const countryFilterWthLang = [
  {
    country: "Afghanistan",
    shortname: "AF",
    countryCode: "+93",
    currency: "Afghani",
    symbol: "؋",
    lang: "fa-AF",
    languages: ["Pashto", "Dari"],
  },
  {
    country: "Albania",
    shortname: "AL",
    countryCode: "+355",
    currency: "Lek",
    symbol: "L",
    lang: "sq-AL",
    languages: ["Albanian"],
  },
  {
    country: "Algeria",
    shortname: "DZ",
    countryCode: "+213",
    currency: "Dinar",
    symbol: "د.ج",
    lang: "ar-DZ",
    languages: ["Arabic", "Berber"],
  },
  {
    country: "Andorra",
    shortname: "AD",
    countryCode: "+376",
    currency: "Euro",
    symbol: "€",
    lang: "ca-AD",
    languages: ["Catalan"],
  },
  {
    country: "Angola",
    shortname: "AO",
    countryCode: "+244",
    currency: "Kwanza",
    symbol: "Kz",
    lang: "pt-AO",
    languages: ["Portuguese"],
  },
  {
    country: "Antigua and Barbuda",
    shortname: "AG",
    countryCode: "+1-268",
    currency: "East Caribbean Dollar",
    symbol: "$",
    lang: "en-AG",
    languages: ["English"],
  },
  {
    country: "Argentina",
    shortname: "AR",
    countryCode: "+54",
    currency: "Peso",
    symbol: "$",
    lang: "es-AR",
    languages: ["Spanish"],
  },
  {
    country: "Armenia",
    shortname: "AM",
    countryCode: "+374",
    currency: "Dram",
    symbol: "֏",
    lang: "hy-AM",
    languages: ["Armenian"],
  },
  {
    country: "Australia",
    shortname: "AU",
    countryCode: "+61",
    currency: "Australian Dollar",
    symbol: "$",
    lang: "en-AU",
    languages: ["English"],
  },
  {
    country: "Austria",
    shortname: "AT",
    countryCode: "+43",
    currency: "Euro",
    symbol: "€",
    lang: "de-AT",
    languages: ["German"],
  },
  {
    country: "Azerbaijan",
    shortname: "AZ",
    countryCode: "+994",
    currency: "Manat",
    symbol: "₼",
    lang: "az-AZ",
    languages: ["Azerbaijani"],
  },
  {
    country: "Bahamas",
    shortname: "BS",
    countryCode: "+1-242",
    currency: "Bahamian Dollar",
    symbol: "$",
    lang: "en-BS",
    languages: ["English"],
  },
  {
    country: "Bahrain",
    shortname: "BH",
    countryCode: "+973",
    currency: "Dinar",
    symbol: "ب.د",
    lang: "ar-BH",
    languages: ["Arabic"],
  },
  {
    country: "Bangladesh",
    shortname: "BD",
    countryCode: "+880",
    currency: "Taka",
    symbol: "৳",
    lang: "bn-BD",
    languages: ["Bengali"],
  },
  {
    country: "Barbados",
    shortname: "BB",
    countryCode: "+1-246",
    currency: "Barbadian Dollar",
    symbol: "$",
    lang: "en-BB",
    languages: ["English"],
  },
  {
    country: "Belarus",
    shortname: "BY",
    countryCode: "+375",
    currency: "Belarusian Ruble",
    symbol: "Br",
    lang: "be-BY",
    languages: ["Belarusian", "Russian"],
  },
  {
    country: "Belgium",
    shortname: "BE",
    countryCode: "+32",
    currency: "Euro",
    symbol: "€",
    lang: "nl-BE",
    languages: ["Dutch", "French", "German"],
  },
  {
    country: "Belize",
    shortname: "BZ",
    countryCode: "+501",
    currency: "Belize Dollar",
    symbol: "$",
    lang: "en-BZ",
    languages: ["English"],
  },
  {
    country: "Benin",
    shortname: "BJ",
    countryCode: "+229",
    currency: "West African CFA Franc",
    symbol: "CFA",
    lang: "fr-BJ",
    languages: ["French"],
  },
  {
    country: "Bhutan",
    shortname: "BT",
    countryCode: "+975",
    currency: "Ngultrum",
    symbol: "Nu.",
    lang: "dz-BT",
    languages: ["Dzongkha"],
  },
  {
    country: "Bolivia",
    shortname: "BO",
    countryCode: "+591",
    currency: "Boliviano",
    symbol: "Bs.",
    lang: "es-BO",
    languages: ["Spanish", "Quechua", "Aymara"],
  },
  {
    country: "Bosnia and Herzegovina",
    shortname: "BA",
    countryCode: "+387",
    currency: "Convertible Mark",
    symbol: "KM",
    lang: "bs-BA",
    languages: ["Bosnian", "Croatian", "Serbian"],
  },
  {
    country: "Botswana",
    shortname: "BW",
    countryCode: "+267",
    currency: "Pula",
    symbol: "P",
    lang: "en-BW",
    languages: ["English", "Tswana"],
  },
  {
    country: "Brazil",
    shortname: "BR",
    countryCode: "+55",
    currency: "Real",
    symbol: "R$",
    lang: "pt-BR",
    languages: ["Portuguese"],
  },
  {
    country: "Brunei",
    shortname: "BN",
    countryCode: "+673",
    currency: "Brunei Dollar",
    symbol: "$",
    lang: "ms-BN",
    languages: ["Malay"],
  },
  {
    country: "Bulgaria",
    shortname: "BG",
    countryCode: "+359",
    currency: "Lev",
    symbol: "лв",
    lang: "bg-BG",
    languages: ["Bulgarian"],
  },
  {
    country: "Burkina Faso",
    shortname: "BF",
    countryCode: "+226",
    currency: "West African CFA Franc",
    symbol: "CFA",
    lang: "fr-BF",
    languages: ["French"],
  },
  {
    country: "Burundi",
    shortname: "BI",
    countryCode: "+257",
    currency: "Burundian Franc",
    symbol: "FBu",
    lang: "fr-BI",
    languages: ["Kirundi", "French"],
  },
  {
    country: "Cabo Verde",
    shortname: "CV",
    countryCode: "+238",
    currency: "Cape Verdean Escudo",
    symbol: "$",
    lang: "pt-CV",
    languages: ["Portuguese"],
  },
  {
    country: "Cambodia",
    shortname: "KH",
    countryCode: "+855",
    currency: "Riel",
    symbol: "៛",
    lang: "km-KH",
    languages: ["Khmer"],
  },
  {
    country: "Cameroon",
    shortname: "CM",
    countryCode: "+237",
    currency: "Central African CFA Franc",
    symbol: "CFA",
    lang: "fr-CM",
    languages: ["French", "English"],
  },
  {
    country: "Canada",
    shortname: "CA",
    countryCode: "+1",
    currency: "Canadian Dollar",
    symbol: "$",
    lang: "en-CA",
    languages: ["English", "French"],
  },
  {
    country: "Central African Republic",
    shortname: "CF",
    countryCode: "+236",
    currency: "Central African CFA Franc",
    symbol: "CFA",
    lang: "fr-CF",
    languages: ["French", "Sango"],
  },
  {
    country: "Chad",
    shortname: "TD",
    countryCode: "+235",
    currency: "Central African CFA Franc",
    symbol: "CFA",
    lang: "fr-TD",
    languages: ["French", "Arabic"],
  },
  {
    country: "Chile",
    shortname: "CL",
    countryCode: "+56",
    currency: "Peso",
    symbol: "$",
    lang: "es-CL",
    languages: ["Spanish"],
  },
  {
    country: "China",
    shortname: "CN",
    countryCode: "+86",
    currency: "Yuan",
    symbol: "¥",
    lang: "zh-CN",
    languages: ["Mandarin"],
  },
  {
    country: "Colombia",
    shortname: "CO",
    countryCode: "+57",
    currency: "Peso",
    symbol: "$",
    lang: "es-CO",
    languages: ["Spanish"],
  },
  {
    country: "Comoros",
    shortname: "KM",
    countryCode: "+269",
    currency: "Comorian Franc",
    symbol: "CF",
    lang: "ar-KM",
    languages: ["Comorian", "Arabic", "French"],
  },
  {
    country: "Congo (Congo-Brazzaville)",
    shortname: "CG",
    countryCode: "+242",
    currency: "Central African CFA Franc",
    symbol: "CFA",
    lang: "fr-CG",
    languages: ["French"],
  },
  {
    country: "Congo (Democratic Republic)",
    shortname: "CD",
    countryCode: "+243",
    currency: "Congolese Franc",
    symbol: "FC",
    lang: "fr-CD",
    languages: ["French"],
  },
  {
    country: "Costa Rica",
    shortname: "CR",
    countryCode: "+506",
    currency: "Costa Rican Colón",
    symbol: "₡",
    lang: "es-CR",
    languages: ["Spanish"],
  },
  {
    country: "Croatia",
    shortname: "HR",
    countryCode: "+385",
    currency: "Euro",
    symbol: "€",
    lang: "hr-HR",
    languages: ["Croatian"],
  },
  {
    country: "Cuba",
    shortname: "CU",
    countryCode: "+53",
    currency: "Cuban Peso",
    symbol: "$",
    lang: "es-CU",
    languages: ["Spanish"],
  },
  {
    country: "Cyprus",
    shortname: "CY",
    countryCode: "+357",
    currency: "Euro",
    symbol: "€",
    lang: "el-CY",
    languages: ["Greek", "Turkish"],
  },
  {
    country: "Czech Republic",
    shortname: "CZ",
    countryCode: "+420",
    currency: "Czech Koruna",
    symbol: "Kč",
    lang: "cs-CZ",
    languages: ["Czech"],
  },
  {
    country: "Denmark",
    shortname: "DK",
    countryCode: "+45",
    currency: "Danish Krone",
    symbol: "kr",
    lang: "da-DK",
    languages: ["Danish"],
  },
  {
    country: "Djibouti",
    shortname: "DJ",
    countryCode: "+253",
    currency: "Djiboutian Franc",
    symbol: "Fdj",
    lang: "fr-DJ",
    languages: ["French", "Arabic"],
  },
  {
    country: "Dominica",
    shortname: "DM",
    countryCode: "+1-767",
    currency: "East Caribbean Dollar",
    symbol: "$",
    lang: "en-DM",
    languages: ["English"],
  },
  {
    country: "Dominican Republic",
    shortname: "DO",
    countryCode: "+1-809",
    currency: "Dominican Peso",
    symbol: "$",
    lang: "es-DO",
    languages: ["Spanish"],
  },
  {
    country: "Ecuador",
    shortname: "EC",
    countryCode: "+593",
    currency: "United States Dollar",
    symbol: "$",
    lang: "es-EC",
    languages: ["Spanish"],
  },
  {
    country: "Egypt",
    shortname: "EG",
    countryCode: "+20",
    currency: "Egyptian Pound",
    symbol: "£",
    lang: "ar-EG",
    languages: ["Arabic"],
  },
  {
    country: "El Salvador",
    shortname: "SV",
    countryCode: "+503",
    currency: "United States Dollar",
    symbol: "$",
    lang: "es-SV",
    languages: ["Spanish"],
  },
  {
    country: "Equatorial Guinea",
    shortname: "GQ",
    countryCode: "+240",
    currency: "Central African CFA Franc",
    symbol: "CFA",
    lang: "es-GQ",
    languages: ["Spanish", "French", "Portuguese"],
  },
  {
    country: "Eritrea",
    shortname: "ER",
    countryCode: "+291",
    currency: "Nakfa",
    symbol: "Nfk",
    lang: "ti-ER",
    languages: ["Tigrinya", "Arabic", "English"],
  },
  {
    country: "Estonia",
    shortname: "EE",
    countryCode: "+372",
    currency: "Euro",
    symbol: "€",
    lang: "et-EE",
    languages: ["Estonian"],
  },
  {
    country: "Eswatini",
    shortname: "SZ",
    countryCode: "+268",
    currency: "Lilangeni",
    symbol: "L",
    lang: "en-SZ",
    languages: ["Swazi", "English"],
  },
  {
    country: "Ethiopia",
    shortname: "ET",
    countryCode: "+251",
    currency: "Birr",
    symbol: "Br",
    lang: "am-ET",
    languages: ["Amharic"],
  },
  {
    country: "Fiji",
    shortname: "FJ",
    countryCode: "+679",
    currency: "Fijian Dollar",
    symbol: "$",
    lang: "en-FJ",
    languages: ["English", "Fijian", "Hindi"],
  },
  {
    country: "Finland",
    shortname: "FI",
    countryCode: "+358",
    currency: "Euro",
    symbol: "€",
    lang: "fi-FI",
    languages: ["Finnish", "Swedish"],
  },
  {
    country: "France",
    shortname: "FR",
    countryCode: "+33",
    currency: "Euro",
    symbol: "€",
    lang: "fr-FR",
    languages: ["French"],
  },
  {
    country: "Gabon",
    shortname: "GA",
    countryCode: "+241",
    currency: "Central African CFA Franc",
    symbol: "CFA",
    lang: "fr-GA",
    languages: ["French"],
  },
  {
    country: "Gambia",
    shortname: "GM",
    countryCode: "+220",
    currency: "Dalasi",
    symbol: "D",
    lang: "en-GM",
    languages: ["English"],
  },
  {
    country: "Georgia",
    shortname: "GE",
    countryCode: "+995",
    currency: "Lari",
    symbol: "₾",
    lang: "ka-GE",
    languages: ["Georgian"],
  },
  {
    country: "Germany",
    shortname: "DE",
    countryCode: "+49",
    currency: "Euro",
    symbol: "€",
    lang: "de-DE",
    languages: ["German"],
  },
  {
    country: "Ghana",
    shortname: "GH",
    countryCode: "+233",
    currency: "Cedi",
    symbol: "₵",
    lang: "en-GH",
    languages: ["English"],
  },
  {
    country: "Greece",
    shortname: "GR",
    countryCode: "+30",
    currency: "Euro",
    symbol: "€",
    lang: "el-GR",
    languages: ["Greek"],
  },
  {
    country: "Grenada",
    shortname: "GD",
    countryCode: "+1-473",
    currency: "East Caribbean Dollar",
    symbol: "$",
    lang: "en-GD",
    languages: ["English"],
  },
  {
    country: "Guatemala",
    shortname: "GT",
    countryCode: "+502",
    currency: "Quetzal",
    symbol: "Q",
    lang: "es-GT",
    languages: ["Spanish"],
  },
  {
    country: "Guinea",
    shortname: "GN",
    countryCode: "+224",
    currency: "Guinean Franc",
    symbol: "FG",
    lang: "fr-GN",
    languages: ["French"],
  },
  {
    country: "Guinea-Bissau",
    shortname: "GW",
    countryCode: "+245",
    currency: "West African CFA Franc",
    symbol: "CFA",
    lang: "pt-GW",
    languages: ["Portuguese"],
  },
  {
    country: "Guyana",
    shortname: "GY",
    countryCode: "+592",
    currency: "Guyanese Dollar",
    symbol: "$",
    lang: "en-GY",
    languages: ["English"],
  },
  {
    country: "Haiti",
    shortname: "HT",
    countryCode: "+509",
    currency: "Gourde",
    symbol: "G",
    lang: "fr-HT",
    languages: ["French", "Haitian Creole"],
  },
  {
    country: "Honduras",
    shortname: "HN",
    countryCode: "+504",
    currency: "Lempira",
    symbol: "L",
    lang: "es-HN",
    languages: ["Spanish"],
  },
  {
    country: "Hungary",
    shortname: "HU",
    countryCode: "+36",
    currency: "Forint",
    symbol: "Ft",
    lang: "hu-HU",
    languages: ["Hungarian"],
  },
  {
    country: "Iceland",
    shortname: "IS",
    countryCode: "+354",
    currency: "Icelandic Króna",
    symbol: "kr",
    lang: "is-IS",
    languages: ["Icelandic"],
  },
  {
    country: "India",
    shortname: "IN",
    countryCode: "+91",
    currency: "Indian Rupee",
    symbol: "₹",
    lang: "hi-IN",
    languages: ["Hindi", "English"],
  },
  {
    country: "Indonesia",
    shortname: "ID",
    countryCode: "+62",
    currency: "Rupiah",
    symbol: "Rp",
    lang: "id-ID",
    languages: ["Indonesian"],
  },
  {
    country: "Iran",
    shortname: "IR",
    countryCode: "+98",
    currency: "Iranian Rial",
    symbol: "﷼",
    lang: "fa-IR",
    languages: ["Persian"],
  },
  {
    country: "Iraq",
    shortname: "IQ",
    countryCode: "+964",
    currency: "Iraqi Dinar",
    symbol: "ع.د",
    lang: "ar-IQ",
    languages: ["Arabic", "Kurdish"],
  },
  {
    country: "Ireland",
    shortname: "IE",
    countryCode: "+353",
    currency: "Euro",
    symbol: "€",
    lang: "ga-IE",
    languages: ["Irish", "English"],
  },
  {
    country: "Israel",
    shortname: "IL",
    countryCode: "+972",
    currency: "Israeli New Shekel",
    symbol: "₪",
    lang: "he-IL",
    languages: ["Hebrew", "Arabic"],
  },
  {
    country: "Italy",
    shortname: "IT",
    countryCode: "+39",
    currency: "Euro",
    symbol: "€",
    lang: "it-IT",
    languages: ["Italian"],
  },
  {
    country: "Jamaica",
    shortname: "JM",
    countryCode: "+1-876",
    currency: "Jamaican Dollar",
    symbol: "$",
    lang: "en-JM",
    languages: ["English"],
  },
  {
    country: "Japan",
    shortname: "JP",
    countryCode: "+81",
    currency: "Yen",
    symbol: "¥",
    lang: "ja-JP",
    languages: ["Japanese"],
  },
  {
    country: "Jordan",
    shortname: "JO",
    countryCode: "+962",
    currency: "Jordanian Dinar",
    symbol: "د.ا",
    lang: "ar-JO",
    languages: ["Arabic"],
  },
  {
    country: "Kazakhstan",
    shortname: "KZ",
    countryCode: "+7",
    currency: "Tenge",
    symbol: "₸",
    lang: "kk-KZ",
    languages: ["Kazakh", "Russian"],
  },
  {
    country: "Kenya",
    shortname: "KE",
    countryCode: "+254",
    currency: "Kenyan Shilling",
    symbol: "KSh",
    lang: "en-KE",
    languages: ["English", "Swahili"],
  },
  {
    country: "Kiribati",
    shortname: "KI",
    countryCode: "+686",
    currency: "Australian Dollar",
    symbol: "$",
    lang: "en-KI",
    languages: ["English"],
  },
  {
    country: "Kuwait",
    shortname: "KW",
    countryCode: "+965",
    currency: "Kuwaiti Dinar",
    symbol: "د.ك",
    lang: "ar-KW",
    languages: ["Arabic"],
  },
  {
    country: "Kyrgyzstan",
    shortname: "KG",
    countryCode: "+996",
    currency: "Som",
    symbol: "сом",
    lang: "ky-KG",
    languages: ["Kyrgyz", "Russian"],
  },
  {
    country: "Laos",
    shortname: "LA",
    countryCode: "+856",
    currency: "Lao Kip",
    symbol: "₭",
    lang: "lo-LA",
    languages: ["Lao"],
  },
  {
    country: "Latvia",
    shortname: "LV",
    countryCode: "+371",
    currency: "Euro",
    symbol: "€",
    lang: "lv-LV",
    languages: ["Latvian"],
  },
  {
    country: "Lebanon",
    shortname: "LB",
    countryCode: "+961",
    currency: "Lebanese Pound",
    symbol: "ل.ل",
    lang: "ar-LB",
    languages: ["Arabic", "French"],
  },
  {
    country: "Lesotho",
    shortname: "LS",
    countryCode: "+266",
    currency: "Lesotho Loti",
    symbol: "L",
    lang: "en-LS",
    languages: ["English", "Sesotho"],
  },
  {
    country: "Liberia",
    shortname: "LR",
    countryCode: "+231",
    currency: "Liberian Dollar",
    symbol: "$",
    lang: "en-LR",
    languages: ["English"],
  },
  {
    country: "Libya",
    shortname: "LY",
    countryCode: "+218",
    currency: "Libyan Dinar",
    symbol: "ل.د",
    lang: "ar-LY",
    languages: ["Arabic"],
  },
  {
    country: "Liechtenstein",
    shortname: "LI",
    countryCode: "+423",
    currency: "Swiss Franc",
    symbol: "CHF",
    lang: "de-LI",
    languages: ["German"],
  },
  {
    country: "Lithuania",
    shortname: "LT",
    countryCode: "+370",
    currency: "Euro",
    symbol: "€",
    lang: "lt-LT",
    languages: ["Lithuanian"],
  },
  {
    country: "Luxembourg",
    shortname: "LU",
    countryCode: "+352",
    currency: "Euro",
    symbol: "€",
    lang: "fr-LU",
    languages: ["Luxembourgish", "French", "German"],
  },
  {
    country: "Madagascar",
    shortname: "MG",
    countryCode: "+261",
    currency: "Malagasy Ariary",
    symbol: "Ar",
    lang: "fr-MG",
    languages: ["Malagasy", "French"],
  },
  {
    country: "Malawi",
    shortname: "MW",
    countryCode: "+265",
    currency: "Malawian Kwacha",
    symbol: "MK",
    lang: "en-MW",
    languages: ["English", "Chichewa"],
  },
  {
    country: "Malaysia",
    shortname: "MY",
    countryCode: "+60",
    currency: "Malaysian Ringgit",
    symbol: "RM",
    lang: "ms-MY",
    languages: ["Malay"],
  },
  {
    country: "Maldives",
    shortname: "MV",
    countryCode: "+960",
    currency: "Maldivian Rufiyaa",
    symbol: "Rf",
    lang: "dv-MV",
    languages: ["Dhivehi"],
  },
  {
    country: "Mali",
    shortname: "ML",
    countryCode: "+223",
    currency: "West African CFA Franc",
    symbol: "CFA",
    lang: "fr-ML",
    languages: ["French"],
  },
  {
    country: "Malta",
    shortname: "MT",
    countryCode: "+356",
    currency: "Euro",
    symbol: "€",
    lang: "mt-MT",
    languages: ["Maltese", "English"],
  },
  {
    country: "Marshall Islands",
    shortname: "MH",
    countryCode: "+692",
    currency: "United States Dollar",
    symbol: "$",
    lang: "en-MH",
    languages: ["Marshallese", "English"],
  },
  {
    country: "Mauritania",
    shortname: "MR",
    countryCode: "+222",
    currency: "Ouguiya",
    symbol: "UM",
    lang: "ar-MR",
    languages: ["Arabic"],
  },
  {
    country: "Mauritius",
    shortname: "MU",
    countryCode: "+230",
    currency: "Mauritian Rupee",
    symbol: "₨",
    lang: "en-MU",
    languages: ["English", "French"],
  },
  {
    country: "Mexico",
    shortname: "MX",
    countryCode: "+52",
    currency: "Mexican Peso",
    symbol: "$",
    lang: "es-MX",
    languages: ["Spanish"],
  },
  {
    country: "Micronesia",
    shortname: "FM",
    countryCode: "+691",
    currency: "United States Dollar",
    symbol: "$",
    lang: "en-FM",
    languages: ["English"],
  },
  {
    country: "Moldova",
    shortname: "MD",
    countryCode: "+373",
    currency: "Moldovan Leu",
    symbol: "L",
    lang: "ro-MD",
    languages: ["Romanian"],
  },
  {
    country: "Monaco",
    shortname: "MC",
    countryCode: "+377",
    currency: "Euro",
    symbol: "€",
    lang: "fr-MC",
    languages: ["French"],
  },
  {
    country: "Mongolia",
    shortname: "MN",
    countryCode: "+976",
    currency: "Tögrög",
    symbol: "₮",
    lang: "mn-MN",
    languages: ["Mongolian"],
  },
  {
    country: "Montenegro",
    shortname: "ME",
    countryCode: "+382",
    currency: "Euro",
    symbol: "€",
    lang: "sr-ME",
    languages: ["Serbian"],
  },
  {
    country: "Morocco",
    shortname: "MA",
    countryCode: "+212",
    currency: "Moroccan Dirham",
    symbol: "د.م.",
    lang: "ar-MA",
    languages: ["Arabic"],
  },
  {
    country: "Mozambique",
    shortname: "MZ",
    countryCode: "+258",
    currency: "Mozambican Metical",
    symbol: "MT",
    lang: "pt-MZ",
    languages: ["Portuguese"],
  },
  {
    country: "Myanmar (Burma)",
    shortname: "MM",
    countryCode: "+95",
    currency: "Kyat",
    symbol: "K",
    lang: "my-MM",
    languages: ["Burmese"],
  },
  {
    country: "Namibia",
    shortname: "NA",
    countryCode: "+264",
    currency: "Namibian Dollar",
    symbol: "$",
    lang: "en-NA",
    languages: ["English"],
  },
  {
    country: "Nauru",
    shortname: "NR",
    countryCode: "+674",
    currency: "Australian Dollar",
    symbol: "$",
    lang: "en-NR",
    languages: ["Nauruan", "English"],
  },
  {
    country: "Nepal",
    shortname: "NP",
    countryCode: "+977",
    currency: "Nepalese Rupee",
    symbol: "₨",
    lang: "ne-NP",
    languages: ["Nepali"],
  },
  {
    country: "Netherlands",
    shortname: "NL",
    countryCode: "+31",
    currency: "Euro",
    symbol: "€",
    lang: "nl-NL",
    languages: ["Dutch"],
  },
  {
    country: "New Zealand",
    shortname: "NZ",
    countryCode: "+64",
    currency: "New Zealand Dollar",
    symbol: "$",
    lang: "en-NZ",
    languages: ["English"],
  },
  {
    country: "Nicaragua",
    shortname: "NI",
    countryCode: "+505",
    currency: "Córdoba",
    symbol: "C$",
    lang: "es-NI",
    languages: ["Spanish"],
  },
  {
    country: "Niger",
    shortname: "NE",
    countryCode: "+227",
    currency: "West African CFA Franc",
    symbol: "CFA",
    lang: "fr-NE",
    languages: ["French"],
  },
  {
    country: "Nigeria",
    shortname: "NG",
    countryCode: "+234",
    currency: "Naira",
    symbol: "₦",
    lang: "en-NG",
    languages: ["English"],
  },
  {
    country: "North Korea",
    shortname: "KP",
    countryCode: "+850",
    currency: "North Korean Won",
    symbol: "₩",
    lang: "ko-KP",
    languages: ["Korean"],
  },
  {
    country: "North Macedonia",
    shortname: "MK",
    countryCode: "+389",
    currency: "Denar",
    symbol: "ден",
    lang: "mk-MK",
    languages: ["Macedonian"],
  },
  {
    country: "Norway",
    shortname: "NO",
    countryCode: "+47",
    currency: "Norwegian Krone",
    symbol: "kr",
    lang: "no-NO",
    languages: ["Norwegian"],
  },
  {
    country: "Oman",
    shortname: "OM",
    countryCode: "+968",
    currency: "Omani Rial",
    symbol: "ر.ع.",
    lang: "ar-OM",
    languages: ["Arabic"],
  },
  {
    country: "Pakistan",
    shortname: "PK",
    countryCode: "+92",
    currency: "Pakistani Rupee",
    symbol: "₨",
    lang: "ur-PK",
    languages: ["Urdu", "English"],
  },
  {
    country: "Palau",
    shortname: "PW",
    countryCode: "+680",
    currency: "United States Dollar",
    symbol: "$",
    lang: "en-PW",
    languages: ["English"],
  },
  {
    country: "Panama",
    shortname: "PA",
    countryCode: "+507",
    currency: "Balboa",
    symbol: "B/.",
    lang: "es-PA",
    languages: ["Spanish"],
  },
  {
    country: "Papua New Guinea",
    shortname: "PG",
    countryCode: "+675",
    currency: "Kina",
    symbol: "K",
    lang: "en-PG",
    languages: ["English", "Tok Pisin", "Hiri Motu"],
  },
  {
    country: "Paraguay",
    shortname: "PY",
    countryCode: "+595",
    currency: "Guarani",
    symbol: "₲",
    lang: "es-PY",
    languages: ["Spanish", "Guarani"],
  },
  {
    country: "Peru",
    shortname: "PE",
    countryCode: "+51",
    currency: "Sol",
    symbol: "S/",
    lang: "es-PE",
    languages: ["Spanish"],
  },
  {
    country: "Philippines",
    shortname: "PH",
    countryCode: "+63",
    currency: "Philippine Peso",
    symbol: "₱",
    lang: "tl-PH",
    languages: ["Filipino", "English"],
  },
  {
    country: "Poland",
    shortname: "PL",
    countryCode: "+48",
    currency: "Polish Zloty",
    symbol: "zł",
    lang: "pl-PL",
    languages: ["Polish"],
  },
  {
    country: "Portugal",
    shortname: "PT",
    countryCode: "+351",
    currency: "Euro",
    symbol: "€",
    lang: "pt-PT",
    languages: ["Portuguese"],
  },
  {
    country: "Qatar",
    shortname: "QA",
    countryCode: "+974",
    currency: "Qatari Riyal",
    symbol: "ر.ق",
    lang: "ar-QA",
    languages: ["Arabic"],
  },
  {
    country: "Romania",
    shortname: "RO",
    countryCode: "+40",
    currency: "Romanian Leu",
    symbol: "lei",
    lang: "ro-RO",
    languages: ["Romanian"],
  },
  {
    country: "Russia",
    shortname: "RU",
    countryCode: "+7",
    currency: "Russian Ruble",
    symbol: "₽",
    lang: "ru-RU",
    languages: ["Russian"],
  },
  {
    country: "Rwanda",
    shortname: "RW",
    countryCode: "+250",
    currency: "Rwandan Franc",
    symbol: "FRw",
    lang: "rw-RW",
    languages: ["Kinyarwanda", "French", "English"],
  },
  {
    country: "Saint Kitts and Nevis",
    shortname: "KN",
    countryCode: "+1-869",
    currency: "East Caribbean Dollar",
    symbol: "$",
    lang: "en-KN",
    languages: ["English"],
  },
  {
    country: "Saint Lucia",
    shortname: "LC",
    countryCode: "+1-758",
    currency: "East Caribbean Dollar",
    symbol: "$",
    lang: "en-LC",
    languages: ["English"],
  },
  {
    country: "Saint Vincent and the Grenadines",
    shortname: "VC",
    countryCode: "+1-784",
    currency: "East Caribbean Dollar",
    symbol: "$",
    lang: "en-VC",
    languages: ["English"],
  },
  {
    country: "Samoa",
    shortname: "WS",
    countryCode: "+685",
    currency: "Tala",
    symbol: "WS$",
    lang: "sm-WS",
    languages: ["Samoan", "English"],
  },
  {
    country: "San Marino",
    shortname: "SM",
    countryCode: "+378",
    currency: "Euro",
    symbol: "€",
    lang: "it-SM",
    languages: ["Italian"],
  },
  {
    country: "Sao Tome and Principe",
    shortname: "ST",
    countryCode: "+239",
    currency: "Dobra",
    symbol: "Db",
    lang: "pt-ST",
    languages: ["Portuguese"],
  },
  {
    country: "Saudi Arabia",
    shortname: "SA",
    countryCode: "+966",
    currency: "Saudi Riyal",
    symbol: "ر.س",
    lang: "ar-SA",
    languages: ["Arabic"],
  },
  {
    country: "Senegal",
    shortname: "SN",
    countryCode: "+221",
    currency: "West African CFA Franc",
    symbol: "CFA",
    lang: "fr-SN",
    languages: ["French"],
  },
  {
    country: "Serbia",
    shortname: "RS",
    countryCode: "+381",
    currency: "Serbian Dinar",
    symbol: "дин",
    lang: "sr-RS",
    languages: ["Serbian"],
  },
  {
    country: "Seychelles",
    shortname: "SC",
    countryCode: "+248",
    currency: "Seychellois Rupee",
    symbol: "SCR",
    lang: "fr-SC",
    languages: ["French", "English"],
  },
  {
    country: "Sierra Leone",
    shortname: "SL",
    countryCode: "+232",
    currency: "Sierra Leonean Leone",
    symbol: "Le",
    lang: "en-SL",
    languages: ["English"],
  },
  {
    country: "Singapore",
    shortname: "SG",
    countryCode: "+65",
    currency: "Singapore Dollar",
    symbol: "S$",
    lang: "en-SG",
    languages: ["English", "Malay", "Mandarin", "Tamil"],
  },
  {
    country: "Slovakia",
    shortname: "SK",
    countryCode: "+421",
    currency: "Euro",
    symbol: "€",
    lang: "sk-SK",
    languages: ["Slovak"],
  },
  {
    country: "Slovenia",
    shortname: "SI",
    countryCode: "+386",
    currency: "Euro",
    symbol: "€",
    lang: "sl-SI",
    languages: ["Slovene"],
  },
  {
    country: "Solomon Islands",
    shortname: "SB",
    countryCode: "+677",
    currency: "Solomon Islands Dollar",
    symbol: "SI$",
    lang: "en-SB",
    languages: ["English"],
  },
  {
    country: "Somalia",
    shortname: "SO",
    countryCode: "+252",
    currency: "Somali Shilling",
    symbol: "Sh",
    lang: "so-SO",
    languages: ["Somali"],
  },
  {
    country: "South Africa",
    shortname: "ZA",
    countryCode: "+27",
    currency: "South African Rand",
    symbol: "R",
    lang: "en-ZA",
    languages: ["English", "Afrikaans", "Zulu", "Xhosa", "Sotho"],
  },
  {
    country: "South Korea",
    shortname: "KR",
    countryCode: "+82",
    currency: "South Korean Won",
    symbol: "₩",
    lang: "ko-KR",
    languages: ["Korean"],
  },
  {
    country: "South Sudan",
    shortname: "SS",
    countryCode: "+211",
    currency: "South Sudanese Pound",
    symbol: "SS£",
    lang: "en-SS",
    languages: ["English"],
  },
  {
    country: "Spain",
    shortname: "ES",
    countryCode: "+34",
    currency: "Euro",
    symbol: "€",
    lang: "es-ES",
    languages: ["Spanish"],
  },
  {
    country: "Sri Lanka",
    shortname: "LK",
    countryCode: "+94",
    currency: "Sri Lankan Rupee",
    symbol: "Rs",
    lang: "si-LK",
    languages: ["Sinhala", "Tamil"],
  },
  {
    country: "Sudan",
    shortname: "SD",
    countryCode: "+249",
    currency: "Sudanese Pound",
    symbol: "SDG",
    lang: "ar-SD",
    languages: ["Arabic"],
  },
  {
    country: "Suriname",
    shortname: "SR",
    countryCode: "+597",
    currency: "Surinamese Dollar",
    symbol: "$",
    lang: "nl-SR",
    languages: ["Dutch"],
  },
  {
    country: "Sweden",
    shortname: "SE",
    countryCode: "+46",
    currency: "Swedish Krona",
    symbol: "kr",
    lang: "sv-SE",
    languages: ["Swedish"],
  },
  {
    country: "Switzerland",
    shortname: "CH",
    countryCode: "+41",
    currency: "Swiss Franc",
    symbol: "CHF",
    lang: "de-CH",
    languages: ["German", "French", "Italian", "Romansh"],
  },
  {
    country: "Syria",
    shortname: "SY",
    countryCode: "+963",
    currency: "Syrian Pound",
    symbol: "£S",
    lang: "ar-SY",
    languages: ["Arabic"],
  },
  {
    country: "Taiwan",
    shortname: "TW",
    countryCode: "+886",
    currency: "New Taiwan Dollar",
    symbol: "NT$",
    lang: "zh-TW",
    languages: ["Mandarin"],
  },
  {
    country: "Tajikistan",
    shortname: "TJ",
    countryCode: "+992",
    currency: "Somoni",
    symbol: "SM",
    lang: "tg-TJ",
    languages: ["Tajik"],
  },
  {
    country: "Tanzania",
    shortname: "TZ",
    countryCode: "+255",
    currency: "Tanzanian Shilling",
    symbol: "TSh",
    lang: "sw-TZ",
    languages: ["Swahili", "English"],
  },
  {
    country: "Thailand",
    shortname: "TH",
    countryCode: "+66",
    currency: "Baht",
    symbol: "฿",
    lang: "th-TH",
    languages: ["Thai"],
  },
  {
    country: "Togo",
    shortname: "TG",
    countryCode: "+228",
    currency: "West African CFA Franc",
    symbol: "CFA",
    lang: "fr-TG",
    languages: ["French"],
  },
  {
    country: "Tonga",
    shortname: "TO",
    countryCode: "+676",
    currency: "Paʻanga",
    symbol: "T$",
    lang: "to-TO",
    languages: ["Tongan"],
  },
  {
    country: "Trinidad and Tobago",
    shortname: "TT",
    countryCode: "+1-868",
    currency: "Trinidad and Tobago Dollar",
    symbol: "$",
    lang: "en-TT",
    languages: ["English"],
  },
  {
    country: "Tunisia",
    shortname: "TN",
    countryCode: "+216",
    currency: "Tunisian Dinar",
    symbol: "د.ت",
    lang: "ar-TN",
    languages: ["Arabic"],
  },
  {
    country: "Turkey",
    shortname: "TR",
    countryCode: "+90",
    currency: "Turkish Lira",
    symbol: "₺",
    lang: "tr-TR",
    languages: ["Turkish"],
  },
  {
    country: "Turkmenistan",
    shortname: "TM",
    countryCode: "+993",
    currency: "Turkmenistani Manat",
    symbol: "T",
    lang: "tk-TM",
    languages: ["Turkmen"],
  },
  {
    country: "Tuvalu",
    shortname: "TV",
    countryCode: "+688",
    currency: "Australian Dollar",
    symbol: "$",
    lang: "en-TV",
    languages: ["Tuvaluan", "English"],
  },
  {
    country: "Uganda",
    shortname: "UG",
    countryCode: "+256",
    currency: "Ugandan Shilling",
    symbol: "USh",
    lang: "en-UG",
    languages: ["English", "Swahili"],
  },
  {
    country: "Ukraine",
    shortname: "UA",
    countryCode: "+380",
    currency: "Ukrainian Hryvnia",
    symbol: "₴",
    lang: "uk-UA",
    languages: ["Ukrainian"],
  },
  {
    country: "United Arab Emirates",
    shortname: "AE",
    countryCode: "+971",
    currency: "United Arab Emirates Dirham",
    symbol: "د.إ",
    lang: "ar-AE",
    languages: ["Arabic"],
  },
  {
    country: "United Kingdom",
    shortname: "GB",
    countryCode: "+44",
    currency: "British Pound Sterling",
    symbol: "£",
    lang: "en-GB",
    languages: ["English"],
  },
  {
    country: "United States",
    shortname: "US",
    countryCode: "+1",
    currency: "United States Dollar",
    symbol: "$",
    lang: "en-US",
    languages: ["English"],
  },
  {
    country: "Uruguay",
    shortname: "UY",
    countryCode: "+598",
    currency: "Peso Uruguayo",
    symbol: "$U",
    lang: "es-UY",
    languages: ["Spanish"],
  },
  {
    country: "Uzbekistan",
    shortname: "UZ",
    countryCode: "+998",
    currency: "Uzbekistani Som",
    symbol: "so'm",
    lang: "uz-UZ",
    languages: ["Uzbek"],
  },
  {
    country: "Vanuatu",
    shortname: "VU",
    countryCode: "+678",
    currency: "Vatu",
    symbol: "VT",
    lang: "bi-VU",
    languages: ["Bislama", "English", "French"],
  },
  {
    country: "Vatican City",
    shortname: "VA",
    countryCode: "+379",
    currency: "Euro",
    symbol: "€",
    lang: "it-VA",
    languages: ["Italian"],
  },
  {
    country: "Venezuela",
    shortname: "VE",
    countryCode: "+58",
    currency: "Venezuelan Bolívar",
    symbol: "Bs",
    lang: "es-VE",
    languages: ["Spanish"],
  },
  {
    country: "Vietnam",
    shortname: "VN",
    countryCode: "+84",
    currency: "Vietnamese Dong",
    symbol: "₫",
    lang: "vi-VN",
    languages: ["Vietnamese"],
  },
  {
    country: "Yemen",
    shortname: "YE",
    countryCode: "+967",
    currency: "Yemeni Rial",
    symbol: "﷼",
    lang: "ar-YE",
    languages: ["Arabic"],
  },
  {
    country: "Zambia",
    shortname: "ZM",
    countryCode: "+260",
    currency: "Zambian Kwacha",
    symbol: "ZK",
    lang: "en-ZM",
    languages: ["English"],
  },
  {
    country: "Zimbabwe",
    shortname: "ZW",
    countryCode: "+263",
    currency: "Zimbabwean Dollar",
    symbol: "Z$",
    lang: "en-ZW",
    languages: ["English"],
  },
];
