export const productActionRequest = {
  CATEGORY_REQUEST_SAGA: "product/CATEGORY_REDUX_SAGA",
  SUB_CATEGORY_REQUEST_SAGA: "product/SUBCATEGORY_WITH_PRODUCTS_SAGA",
  SUB_CATEGORY_ALl_DATA_REQUEST_SAGA:
    "product/SUBCATEGORY_WITH_ALL_PRODUCTS_SAGA",
  GET_WHITELIST_REQUEST_SAGA: "product/GET_WHITELIST_SAGA",
  ADD_WHITELIST_REQUEST_SAGA: "product/ADD_WHITELIST_SAGA",
  REMOVE_WHITELIST_REQUEST_SAGA: "product/REMOVE_WHITELIST_SAGA",
};
export const productActionSuccess = {
  CATEGORY_REQUEST_SUCCESS: "product/CATEGORY_REDUX",
  SUB_CATEGORY_REQUEST_SUCCESS: "product/SUBCATEGORY_WITH_PRODUCTS",
  SUB_CATEGORY_ALL_DATA_REQUEST_SUCCESS:
    "product/SUBCATEGORY_WITH_ALL_PRODUCTS",
  GET_WHITELIST_SUCCESS: "product/GET_WHITELIST",
  ADD_WHITELIST_SUCCESS: "product/ADD_WHITELIST",
  REMOVE_WHITELIST_SUCCESS: "product/REMOVE_WHITELIST",
};
