export const productActionRequest = {
  CATEGORY_REQUEST_SAGA: "product/CATEGORY_REDUX_SAGA",
  SUB_CATEGORY_REQUEST_SAGA: "product/SUBCATEGORY_WITH_PRODUCTS_SAGA",
  SUB_CATEGORY_ALl_DATA_REQUEST_SAGA:
    "product/SUBCATEGORY_WITH_ALL_PRODUCTS_SAGA",
};
export const productActionSuccess = {
  CATEGORY_REQUEST_SUCCESS: "product/CATEGORY_REDUX",
  SUB_CATEGORY_REQUEST_SUCCESS: "product/SUBCATEGORY_WITH_PRODUCTS",
  SUB_CATEGORY_ALL_DATA_REQUEST_SUCCESS:
    "product/SUBCATEGORY_WITH_ALL_PRODUCTS",
};
