export const SellerProductAction = {
  AddNewProductSellerSaga: "AddNewProductSellerSaga",
  GET_DASHBOARD_DETAILS_SAGA: "GET_DASHBOARD_DETAILS_SAGA",
  GET_ALL_PRODUCTS_SAGA: "GET_ALL_PRODUCTS_SAGA",
  GET_SINGLE_PRODUCT_SAGA: "GET_SINGLE_PRODUCT_SAGA",
  UPDATE_SELLER_PRODUCTS_SAGA: "UPDATE_SELLER_PRODUCTS_SAGA",
  UPDATE_SELLER_BRAND_LOGO_SAGA: "UPDATE_SELLER_BRAND_LOGO_SAGA",
  UPDATE_SELLER_THUMBNAIL_SAGA: "UPDATE_SELLER_THUMBNAIL_SAGA",
  UPDATE_SELLER_MULTIPLE_IMAGES_SAGA: "UPDATE_SELLER_MULTIPLE_IMAGES_SAGA",
  DELETE_SELLER_PRODUCT_SAGA: "DELETE_SELLER_PRODUCT_SAGA",
};
