export const SellerAuthActionSuccess = {
  SELLER_PROFILE_SAGA_SUCCESS: "SELLER_PROFILE_SAGA_SUCCESS",
  UPDATE_PROFILE_SAGA_SUCCESS: "UPDATE_PROFILE_SAGA_SUCCESS",
  GET_SINGLE_DETAILS_SAGA_SUCCESS: "GET_SINGLE_DETAILS_SAGA_SUCCESS",
  UPDATE_SELLER_DETAILS_SAGA_SUCCESS: "UPDATE_SELLER_DETAILS_SAGA_SUCCESS",
};
export const SellerAuthActionRequest = {
  SELLER_PROFILE_SAGA_REQUEST: "sellerAuth/SELLER_PROFILE_SAGA_REQUEST",
  UPDATE_PROFILE_SAGA_REQUEST: "UPDATE_PROFILE_SAGA_REQUEST",
  GET_SINGLE_DETAILS_SAGA_REQUEST: "GET_SINGLE_DETAILS_SAGA_REQUEST",
  UPDATE_SELLER_DETAILS_SAGA_REQUEST: "UPDATE_SELLER_DETAILS_SAGA_REQUEST",
};

export const SellerAuthActionError = {
  SELLER_PROFILE_SAGA_ERROR: "SELLER_PROFILE_SAGA_ERROR",
  UPDATE_PROFILE_SAGA_ERROR: "UPDATE_PROFILE_SAGA_ERROR",
  GET_SINGLE_DETAILS_SAGA_ERROR: "GET_SINGLE_DETAILS_SAGA_ERROR",
  UPDATE_SELLER_DETAILS_SAGA_ERROR: "UPDATE_SELLER_DETAILS_SAGA_ERROR",
};
