export const SellerProductActionSuccess = {
  AddNewProductSellerSaga: "AddNewProductSellerSaga",
  GET_DASHBOARD_DETAILS_SAGA_SUCCESS: "GET_DASHBOARD_DETAILS_SAGA_SUCCESS",
  GET_ALL_PRODUCTS_SAGA_SUCCESS: "GET_ALL_PRODUCTS_SAGA_SUCCESS",
  GET_SINGLE_PRODUCT_SAGA_SUCCESS: "GET_SINGLE_PRODUCT_SAGA_SUCCESS",
  UPDATE_SELLER_PRODUCTS_SAGA_SUCCESS: "UPDATE_SELLER_PRODUCTS_SAGA_SUCCESS",
  UPDATE_SELLER_BRAND_LOGO_SAGA_SUCCESS:
    "UPDATE_SELLER_BRAND_LOGO_SAGA_SUCCESS",
  UPDATE_SELLER_THUMBNAIL_SAGA_SUCCESS: "UPDATE_SELLER_THUMBNAIL_SAGA_SUCCESS",
  UPDATE_SELLER_MULTIPLE_IMAGES_SAGA_SUCCESS:
    "UPDATE_SELLER_MULTIPLE_IMAGES_SAGA_SUCCESS",
  DELETE_SELLER_PRODUCT_SAGA_SUCCESS: "DELETE_SELLER_PRODUCT_SAGA_SUCCESS",
};
export const SellerProductActionRequest = {
  AddNewProductSellerSaga: "sProduct/AddNewProductSellerSaga",
  GET_DASHBOARD_DETAILS_SAGA_REQUEST: "GET_DASHBOARD_DETAILS_SAGA_REQUEST",
  GET_ALL_PRODUCTS_SAGA_REQUEST: "GET_ALL_PRODUCTS_SAGA_REQUEST",
  GET_SINGLE_PRODUCT_SAGA_REQUEST: "GET_SINGLE_PRODUCT_SAGA_REQUEST",
  UPDATE_SELLER_PRODUCTS_SAGA_REQUEST: "UPDATE_SELLER_PRODUCTS_SAGA_REQUEST",
  UPDATE_SELLER_BRAND_LOGO_SAGA_REQUEST:
    "UPDATE_SELLER_BRAND_LOGO_SAGA_REQUEST",
  UPDATE_SELLER_THUMBNAIL_SAGA_REQUEST: "UPDATE_SELLER_THUMBNAIL_SAGA_REQUEST",
  UPDATE_SELLER_MULTIPLE_IMAGES_SAGA_REQUEST:
    "UPDATE_SELLER_MULTIPLE_IMAGES_SAGA_REQUEST",
  DELETE_SELLER_PRODUCT_SAGA_REQUEST: "DELETE_SELLER_PRODUCT_SAGA_REQUEST",
};
export const SellerProductActionError = {
  AddNewProductSellerSaga_ERROR: "sProduct/AddNewProductSellerSaga_ERROR",
  GET_DASHBOARD_DETAILS_SAGA_ERROR: "GET_DASHBOARD_DETAILS_SAGA_ERROR",
  GET_ALL_PRODUCTS_SAGA_ERROR: "GET_ALL_PRODUCTS_SAGA_ERROR",
  GET_SINGLE_PRODUCT_SAGA_ERROR: "GET_SINGLE_PRODUCT_SAGA_ERROR",
  UPDATE_SELLER_PRODUCTS_SAGA_ERROR: "UPDATE_SELLER_PRODUCTS_SAGA_ERROR",
  UPDATE_SELLER_BRAND_LOGO_SAGA_ERROR: "UPDATE_SELLER_BRAND_LOGO_SAGA_ERROR",
  UPDATE_SELLER_THUMBNAIL_SAGA_ERROR: "UPDATE_SELLER_THUMBNAIL_SAGA_ERROR",
  UPDATE_SELLER_MULTIPLE_IMAGES_SAGA_ERROR:
    "UPDATE_SELLER_MULTIPLE_IMAGES_SAGA_ERROR",
  DELETE_SELLER_PRODUCT_SAGA_ERROR: "DELETE_SELLER_PRODUCT_SAGA_ERROR",
};
