export const GET_TABLE_PRODUCT_LOADING = "GET_TABLE_PRODUCT_LOADING";
export const GET_TABLE_PRODUCT_FULLFIELD = "GET_TABLE_PRODUCT_FULLFIELD";
export const GET_TABLE_PRODUCT_ERROR = "GET_TABLE_PRODUCT_ERROR";
export const POST_NEW_PRODUCT_LOADING = "POST_NEW_PRODUCT_LOADING";
export const POST_NEW_PRODUCT_FULLFIELD = "POST_NEW_PRODUCT_FULLFIELD";
export const POST_NEW_PRODUCT_ERROR = "POST_NEW_PRODUCT_ERROR";
